// Code generated by MockGen. DO NOT EDIT.
// Source: pgxpool_iter_query.go
//
// Generated by this command:
//
//	mockgen -source=pgxpool_iter_query.go --destination ../../../internal/mocks/mock_pgx_tx.go --package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pgconn "github.com/jackc/pgx/v5/pgconn"
	gomock "go.uber.org/mock/gomock"
)

// MockPgxExec is a mock of PgxExec interface.
type MockPgxExec struct {
	ctrl     *gomock.Controller
	recorder *MockPgxExecMockRecorder
	isgomock struct{}
}

// MockPgxExecMockRecorder is the mock recorder for MockPgxExec.
type MockPgxExecMockRecorder struct {
	mock *MockPgxExec
}

// NewMockPgxExec creates a new mock instance.
func NewMockPgxExec(ctrl *gomock.Controller) *MockPgxExec {
	mock := &MockPgxExec{ctrl: ctrl}
	mock.recorder = &MockPgxExecMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPgxExec) EXPECT() *MockPgxExecMockRecorder {
	return m.recorder
}

// Exec mocks base method.
func (m *MockPgxExec) Exec(ctx context.Context, sql string, arguments ...any) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, sql}
	for _, a := range arguments {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockPgxExecMockRecorder) Exec(ctx, sql any, arguments ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, sql}, arguments...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockPgxExec)(nil).Exec), varargs...)
}
