// Code generated by MockGen. DO NOT EDIT.
// Source: internal/cachecontroller/cache_controller.go
//
// Generated by this command:
//
//	mockgen -source internal/cachecontroller/cache_controller.go -destination internal/mocks/mock_cachecontroller.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCacheController is a mock of CacheController interface.
type MockCacheController struct {
	ctrl     *gomock.Controller
	recorder *MockCacheControllerMockRecorder
	isgomock struct{}
}

// MockCacheControllerMockRecorder is the mock recorder for MockCacheController.
type MockCacheControllerMockRecorder struct {
	mock *MockCacheController
}

// NewMockCacheController creates a new mock instance.
func NewMockCacheController(ctrl *gomock.Controller) *MockCacheController {
	mock := &MockCacheController{ctrl: ctrl}
	mock.recorder = &MockCacheControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheController) EXPECT() *MockCacheControllerMockRecorder {
	return m.recorder
}

// DetermineInvalidationTime mocks base method.
func (m *MockCacheController) DetermineInvalidationTime(arg0 context.Context, arg1 string) time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetermineInvalidationTime", arg0, arg1)
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// DetermineInvalidationTime indicates an expected call of DetermineInvalidationTime.
func (mr *MockCacheControllerMockRecorder) DetermineInvalidationTime(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetermineInvalidationTime", reflect.TypeOf((*MockCacheController)(nil).DetermineInvalidationTime), arg0, arg1)
}

// InvalidateIfNeeded mocks base method.
func (m *MockCacheController) InvalidateIfNeeded(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateIfNeeded", arg0, arg1)
}

// InvalidateIfNeeded indicates an expected call of InvalidateIfNeeded.
func (mr *MockCacheControllerMockRecorder) InvalidateIfNeeded(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateIfNeeded", reflect.TypeOf((*MockCacheController)(nil).InvalidateIfNeeded), arg0, arg1)
}
