-- +goose Up
ALTER TABLE tuple MODIFY COLUMN inserted_at TIMESTAMP(6) NOT NULL;

ALTER TABLE store
    MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL,
    MODIFY COLUMN updated_at TIMESTAMP(6),
    MODIFY COLUMN deleted_at TIMESTAMP(6);

ALTER TABLE changelog MODIFY COLUMN inserted_at TIMESTAMP(6) NOT NULL;

-- +goose Down
ALTER TABLE tuple MODIFY COLUMN inserted_at TIMESTAMP NOT NULL;

ALTER TABLE store
    MODIFY COLUMN created_at TIMESTAMP NOT NULL,
    MODIFY COLUMN updated_at TIMESTAMP,
    MODIFY COLUMN deleted_at TIMESTAMP;

ALTER TABLE changelog MODIFY COLUMN inserted_at TIMESTAMP NOT NULL;
