header:
  schema-version: 2.0.0
  last-updated: '2025-07-26'
  last-reviewed: '2025-07-26'
  url: https://github.com/openfga/openfga
  project-si-source: https://raw.githubusercontent.com/openfga/.github/main/SECURITY-INSIGHTS.yml
  comment: High-performance and flexible authorization engine built for developers and inspired by Google Zanzibar.

repository:
  url: https://github.com/openfga/openfga
  status: active
  bug-fixes-only: false
  accepts-change-request: true
  accepts-automated-change-request: true
  no-third-party-packages: false
  core-team:
  - name: Poovamraj Thanganadar Thiagarajan
    affiliation: Okta
    email: poovamraj.thanganadarthiagarajan@okta.com
    social: https://github.com/poovamraj
    primary: true
  - name: Adrian Tam
    affiliation: Okta
    email: adrian.tam@okta.com
    social: https://github.com/adriantam
  - name: Dan Cech
    affiliation: Grafana Labs
    email: dcech@grafana.com
    social: https://github.com/DanCech
  - name: Jose Padilla
    affiliation: Okta
    email: jose.padilla@okta.com
    social: https://github.com/jpadilla
  - name: Joshua Jones
    affiliation: Okta
    email: joshua.jones@okta.com
    social: https://github.com/senojj
  - name: Justin Cohen
    affiliation: Okta
    email: justin.cohen@okta.com
    social: https://github.com/justincoh
  - name: Raghd Hamzeh
    affiliation: Okta
    email: raghd.hamzeh@okta.com
    social: https://github.com/rhamzeh
  - name: Victoria Johns
    affiliation: Okta
    email: victoria.johns@okta.com
    social: https://github.com/vic-dev
  - name: Will Vedder
    affiliation: Okta
    email: will.vedder@okta.com
    social: https://github.com/willvedd
  - name: Yamil Asusta
    affiliation: Okta
    email: yamil.asusta@okta.com
    social: https://github.com/elbuo8
  - name: Yissell Garma
    affiliation: Okta
    email: yissell.garma@okta.com
    social: https://github.com/yissellokta
  - name: Zilvinas Vilutis
    affiliation: Okta
    email: zilvinas.vilutis@okta.com
    social: https://github.com/cikasfm

  license:
    url: https://raw.githubusercontent.com/openfga/openfga/main/LICENSE
    expression: Apache-2.0
  release:
    changelog: https://github.com/openfga/openfga/releases
    automated-pipeline: true
    distribution-points:
      - uri: https://github.com/openfga/openfga/releases
        comment: GitHub Release Page

  documentation:
    contributing-guide: https://github.com/openfga/.github/blob/main/CONTRIBUTING.md
    dependency-management-policy: https://github.com/openfga/openfga/blob/main/docs/dependencies-policy.md
    governance: https://github.com/openfga/.github/blob/main/GOVERNANCE.md
    review-policy: https://github.com/openfga/.github/blob/main/CONTRIBUTING.md
    security-policy: https://github.com/openfga/openfga/SECURITY.md

  security:
    assessments:
      self:
        evidence: https://github.com/cncf/tag-security/blob/main/community/assessments/projects/openfga/joint-assessment.md
        date: '2024-12-19'
        comment: OpenFGA has completed a CNCF security join assessment with CNCF TAG-Security

    champions:
      - name: Justin Cohen
        email: justin.cohen@okta.com
        primary: true
    tools:
      - name: Dependabot
        type: SCA
        version: latest
        rulesets:
          - built-in
        integration:
          adhoc: false
          ci: true
          release: true
        comment: Dependabot is enabled for this repository to automatically update dependencies.
      - name: Snyk
        type: SCA
        version: latest
        rulesets:
          - built-in
        integration:
          adhoc: false
          ci: true
          release: true
        comment: Snyk is enabled for this repository to scan for vulnerabilities.
