run:
  timeout: 3m
  modules-download-mode: readonly
  allow-parallel-runners: true
  build-tags:
    - docker

linters:
  enable:
    - errname
    - gofmt
    - gci
    - gofumpt
    - stylecheck
    - importas
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - mirror
    - misspell
    - staticcheck
    - tagalign
    - testifylint
    - typecheck
    - unused
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - protogetter
    # TODO enable https://github.com/openfga/openfga/issues/598
    # - bodyclose
    # - contextcheck
    # - exhaustive
    # - errorlint
    # - gochecknoglobals
    # - gocritic
    # - godot
    # - gosec
    # - noctx
    # - inamedparam
    # - perfsprint
    # - prealloc
    # - tparallel
linters-settings:
  gci:
    sections:
      - standard                            # Standard section: captures all standard packages.
      - default                             # Default section: contains all imports that could not be matched to another section type.
      - blank                               # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
      - dot                                 # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
      - prefix(github.com/openfga/openfga)  # Custom section: groups all imports with the specified Prefix.
  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment
  goimports:
    local-prefixes: "github.com/openfga/openfga"
  importas:
    # Do not allow unaliased imports of aliased packages.
    no-unaliased: true
    # Do not allow non-required aliases.
    no-extra-aliases: false
    alias:
      - pkg: github.com/openfga/api/proto/openfga/v1
        alias: openfgav1
