run:
  timeout: 3m
  modules-download-mode: readonly

linters:
  enable:
    - errname
    - forbidigo
    - gofmt
    - goimports
    - stylecheck

linters-settings:
  forbidigo:
    forbid:
      - '^fmt\.Errorf$'
