project_name: openfga

before:
  hooks:
    - make install-tools
    - go generate ./...

builds:
  - 
    main: ./cmd/openfga
    binary: bin/openfga
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-s -w"
      - "-X github.com/openfga/openfga/internal/build.Version=v{{ .Version }}"
      - "-X github.com/openfga/openfga/internal/build.Commit={{.Commit}}"
      - "-X github.com/openfga/openfga/internal/build.Date={{.Date}}"

dockers:
  -
    goos: linux
    goarch: amd64

    dockerfile: Dockerfile.goreleaser

    image_templates:
      - "openfga/openfga:latest"
      - "openfga/openfga:{{ .Tag }}"
      - "openfga/openfga:v{{ .Version }}"
      - "openfga/openfga:v{{ .Major }}"
      - "openfga/openfga:v{{ .Major }}.{{ .Minor }}"
      - "openfga/openfga:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"

    extra_files:
      - static/playground

release:
  github:
    owner: openfga
    name: openfga

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
