project_name: openfga

before:
  hooks:
    - make install-tools
    - go generate ./...

builds:
  - 
    main: ./cmd/openfga
    binary: openfga
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-s -w"
      - "-X github.com/openfga/openfga/internal/build.Version=v{{ .Version }}"
      - "-X github.com/openfga/openfga/internal/build.Commit={{.Commit}}"
      - "-X github.com/openfga/openfga/internal/build.Date={{.Date}}"

dockers:
  - goos: linux
    goarch: amd64

    dockerfile: Dockerfile.goreleaser

    image_templates:
      - "openfga/openfga:latest-amd64"
      - "openfga/openfga:{{ .Tag }}-amd64"
      - "openfga/openfga:v{{ .Version }}-amd64"
      - "openfga/openfga:v{{ .Major }}-amd64"
      - "openfga/openfga:v{{ .Major }}.{{ .Minor }}-amd64"
      - "openfga/openfga:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64"

    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg"
      - "OS=linux"
      - "--build-arg"
      - "ARCH=amd64"

    extra_files:
      - assets

  - goos: linux
    goarch: arm64

    dockerfile: Dockerfile.goreleaser

    image_templates:
      - "openfga/openfga:latest-arm64"
      - "openfga/openfga:{{ .Tag }}-arm64"
      - "openfga/openfga:v{{ .Version }}-arm64"
      - "openfga/openfga:v{{ .Major }}-arm64"
      - "openfga/openfga:v{{ .Major }}.{{ .Minor }}-arm64"
      - "openfga/openfga:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64"

    use: buildx

    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg"
      - "OS=linux"
      - "--build-arg"
      - "ARCH=arm64"

    extra_files:
      - assets

docker_manifests:
  - name_template: openfga/openfga:latest
    image_templates:
      - openfga/openfga:latest-amd64
      - openfga/openfga:latest-arm64
  - name_template: openfga/openfga:v{{ .Version }}
    image_templates:
      - openfga/openfga:v{{ .Version }}-amd64
      - openfga/openfga:v{{ .Version }}-arm64
  - name_template: openfga/openfga:v{{ .Major }}
    image_templates:
      - openfga/openfga:v{{ .Major }}-amd64
      - openfga/openfga:v{{ .Major }}-arm64
  - name_template: openfga/openfga:v{{ .Major }}.{{ .Minor }}
    image_templates:
      - openfga/openfga:v{{ .Major }}.{{ .Minor }}-amd64
      - openfga/openfga:v{{ .Major }}.{{ .Minor }}-arm64
  - name_template: openfga/openfga:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}
    image_templates:
      - openfga/openfga:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-amd64
      - openfga/openfga:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-arm64

release:
  github:
    owner: openfga
    name: openfga

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - assets

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
