ignore:
  # the following folders contain tests that need to be exported so that consumer modules can run them with their own storage implementation
  - "pkg/storage/test"
  - "pkg/server/test"
  - "tests"
  # the following file is only used for local testing of the grpc storage server
  - "cmd/grpc-storage-server/main.go"
  # the following folder contains helper test code
  - "pkg/testfixtures/storage"
coverage:
  range: 70..85
  round: up
  precision: 2
  status:
    project:
      default:
        target: 85%
