FROM cgr.dev/chainguard/static:latest
COPY assets /assets
COPY openfga /
COPY --from=ghcr.io/grpc-ecosystem/grpc-health-probe:v0.4.16 /ko-app/grpc-health-probe /usr/local/bin/grpc_health_probe
ENTRYPOINT ["/openfga"]
