FROM cgr.dev/chainguard/static@sha256:77d8b8925dc27970ec2f48243f44c7a260d52c49cd778288e4ee97566e0cb75b
COPY assets /assets
COPY openfga /

# Goreleaser does not support multi-stage builds. See:
# https://github.com/goreleaser/goreleaser/issues/609
#
# Dependabot is also not capable of updating inline image copies at this time, so
# this needs to be updated manually until one of these issues is resolved.
COPY --from=ghcr.io/grpc-ecosystem/grpc-health-probe:v0.4.52@sha256:0303b506a288d544ed99fef17a55c8c5ce872f498f643c396b532b3595089ac9 /ko-app/grpc-health-probe /usr/local/bin/grpc_health_probe
ENTRYPOINT ["/openfga"]
