FROM cgr.dev/chainguard/static@sha256:9cef3c6a78264cb7e25923bf1bf7f39476dccbcc993af9f4ffeb191b77a7951e
COPY assets /assets
COPY openfga /

# Goreleaser does not support multi-stage builds. See:
# https://github.com/goreleaser/goreleaser/issues/609
#
# Dependabot is also not capable of updating inline image copies at this time, so
# this needs to be updated manually until one of these issues is resolved.
COPY --from=ghcr.io/grpc-ecosystem/grpc-health-probe:v0.4.44@sha256:071e96cdcf1d40aacd59ce556b8843f54acb1ea511d04d0db188aa2621c00c32 /ko-app/grpc-health-probe /usr/local/bin/grpc_health_probe
ENTRYPOINT ["/openfga"]
