name: 🐛 Report a bug
description: If you are reporting that Check, ListObjects or ListUsers API are returning unexpected responses, please report a security vulnerability instead
labels: [ "bug" ]

body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have looked into the [README](https://github.com/openfga/openfga/blob/main/README.md) and have not found a suitable solution or answer.
          required: true
        - label: I have looked into the [documentation](https://openfga.dev/docs) and have not found a suitable solution or answer.
          required: true
        - label: I have searched the [issues](https://github.com/openfga/openfga/issues) and have not found a suitable solution or answer.
          required: true
        - label: I have upgraded to the [latest version](https://github.com/openfga/openfga/releases/latest) of OpenFGA and the issue still persists.
          required: true
        - label: I have searched the [OpenFGA Community](https://openfga.dev/community) and have not found a suitable solution or answer.
          required: true
        - label: I agree to the terms within the [OpenFGA Code of Conduct](https://github.com/openfga/.github/blob/main/CODE_OF_CONDUCT.md).
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe how to reproduce your issue, what you are seeing and what you expected to see. If you are reporting that Check, ListObjects or ListUsers API are returning unexpected responses, please report a security vulnerability instead
    validations:
      required: true

  - type: input
    id: environment-openfga-version
    attributes:
      label: OpenFGA version
      description: The version of OpenFGA you're using.
    validations:
      required: true

  - type: dropdown
    id: environment-openfga-runnable
    attributes:
      label: How are you running OpenFGA?
      options:
        - As a binary
        - In Docker
        - In Kubernetes
    validations:
      required: true

  - type: dropdown
    id: environment-datastore-version
    attributes:
      label: What datastore are you using?
      options:
        - In-Memory
        - MySQL
        - Postgres
        - SQLite
    validations:
      required: true

  - type: input
    id: environment-openfga-flags
    attributes:
      label: OpenFGA Flags
      description: Are you running OpenFGA with any configuration overrides or with any of the flags mentioned in `./openfga run --help`?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Do you have any logs or traces that could help us debug the problem?
    validations:
      required: false
