// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openfga/openfga/internal/check (interfaces: CheckResolver)
//
// Generated by this command:
//
//	mockgen -package=check -destination=internal/check/mock_resolver.go github.com/openfga/openfga/internal/check CheckResolver
//

// Package check is a generated GoMock package.
package check

import (
	context "context"
	reflect "reflect"
	sync "sync"

	graph "github.com/openfga/language/pkg/go/graph"
	gomock "go.uber.org/mock/gomock"
)

// MockCheckResolver is a mock of CheckResolver interface.
type MockCheckResolver struct {
	ctrl     *gomock.Controller
	recorder *MockCheckResolverMockRecorder
	isgomock struct{}
}

// MockCheckResolverMockRecorder is the mock recorder for MockCheckResolver.
type MockCheckResolverMockRecorder struct {
	mock *MockCheckResolver
}

// NewMockCheckResolver creates a new mock instance.
func NewMockCheckResolver(ctrl *gomock.Controller) *MockCheckResolver {
	mock := &MockCheckResolver{ctrl: ctrl}
	mock.recorder = &MockCheckResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckResolver) EXPECT() *MockCheckResolverMockRecorder {
	return m.recorder
}

// ResolveCheck mocks base method.
func (m *MockCheckResolver) ResolveCheck(arg0 context.Context, arg1 *Request) (*Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveCheck", arg0, arg1)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveCheck indicates an expected call of ResolveCheck.
func (mr *MockCheckResolverMockRecorder) ResolveCheck(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveCheck", reflect.TypeOf((*MockCheckResolver)(nil).ResolveCheck), arg0, arg1)
}

// ResolveUnion mocks base method.
func (m *MockCheckResolver) ResolveUnion(arg0 context.Context, arg1 *Request, arg2 *graph.WeightedAuthorizationModelNode, arg3 *sync.Map) (*Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveUnion", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveUnion indicates an expected call of ResolveUnion.
func (mr *MockCheckResolverMockRecorder) ResolveUnion(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveUnion", reflect.TypeOf((*MockCheckResolver)(nil).ResolveUnion), arg0, arg1, arg2, arg3)
}
