// Code generated by MockGen. DO NOT EDIT.
// Source: internal/check/interface.go
//
// Generated by this command:
//
//	mockgen --source=internal/check/interface.go --destination=internal/check/mock_resolver.go
//

// Package mock_check is a generated GoMock package.
package check

import (
	context "context"
	reflect "reflect"
	sync "sync"

	graph "github.com/openfga/language/pkg/go/graph"
	storage "github.com/openfga/openfga/pkg/storage"
	gomock "go.uber.org/mock/gomock"
)

// MockCheckResolver is a mock of CheckResolver interface.
type MockCheckResolver struct {
	ctrl     *gomock.Controller
	recorder *MockCheckResolverMockRecorder
	isgomock struct{}
}

// MockCheckResolverMockRecorder is the mock recorder for MockCheckResolver.
type MockCheckResolverMockRecorder struct {
	mock *MockCheckResolver
}

// NewMockCheckResolver creates a new mock instance.
func NewMockCheckResolver(ctrl *gomock.Controller) *MockCheckResolver {
	mock := &MockCheckResolver{ctrl: ctrl}
	mock.recorder = &MockCheckResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckResolver) EXPECT() *MockCheckResolverMockRecorder {
	return m.recorder
}

// ResolveCheck mocks base method.
func (m *MockCheckResolver) ResolveCheck(arg0 context.Context, arg1 *Request) (*Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveCheck", arg0, arg1)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveCheck indicates an expected call of Resolve
func (mr *MockCheckResolverMockRecorder) ResolveCheck(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveCheck", reflect.TypeOf((*MockCheckResolver)(nil).ResolveCheck), arg0, arg1)
}

// ResolveEdge mocks base method.
func (m *MockCheckResolver) ResolveEdge(arg0 context.Context, arg1 *Request, arg2 *graph.WeightedAuthorizationModelEdge, arg3 *sync.Map) (*Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveEdge", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveEdge indicates an expected call of ResolveEdge.
func (mr *MockCheckResolverMockRecorder) ResolveEdge(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveEdge", reflect.TypeOf((*MockCheckResolver)(nil).ResolveEdge), arg0, arg1, arg2, arg3)
}

// ResolveExclusionEdges mocks base method.
func (m *MockCheckResolver) ResolveExclusionEdges(arg0 context.Context, arg1 *Request, arg2 []LogicalEdge) (*Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveExclusionEdges", arg0, arg1, arg2)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveExclusionEdges indicates an expected call of ResolveExclusionEdges.
func (mr *MockCheckResolverMockRecorder) ResolveExclusionEdges(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveExclusionEdges", reflect.TypeOf((*MockCheckResolver)(nil).ResolveExclusionEdges), arg0, arg1, arg2)
}

// ResolveIntersectionEdges mocks base method.
func (m *MockCheckResolver) ResolveIntersectionEdges(arg0 context.Context, arg1 *Request, arg2 []LogicalEdge) (*Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveIntersectionEdges", arg0, arg1, arg2)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveIntersectionEdges indicates an expected call of ResolveIntersectionEdges.
func (mr *MockCheckResolverMockRecorder) ResolveIntersectionEdges(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveIntersectionEdges", reflect.TypeOf((*MockCheckResolver)(nil).ResolveIntersectionEdges), arg0, arg1, arg2)
}

// ResolveUnion mocks base method.
func (m *MockCheckResolver) ResolveUnion(arg0 context.Context, arg1 *Request, arg2 *graph.WeightedAuthorizationModelNode, arg3 *sync.Map) (*Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveUnion", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveUnion indicates an expected call of ResolveUnion.
func (mr *MockCheckResolverMockRecorder) ResolveUnion(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveUnion", reflect.TypeOf((*MockCheckResolver)(nil).ResolveUnion), arg0, arg1, arg2, arg3)
}

// ResolveUnionEdges mocks base method.
func (m *MockCheckResolver) ResolveUnionEdges(arg0 context.Context, arg1 *Request, arg2 []LogicalEdge, arg3 *sync.Map) (*Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveUnionEdges", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveUnionEdges indicates an expected call of ResolveUnionEdges.
func (mr *MockCheckResolverMockRecorder) ResolveUnionEdges(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveUnionEdges", reflect.TypeOf((*MockCheckResolver)(nil).ResolveUnionEdges), arg0, arg1, arg2, arg3)
}

// MockGroupStrategy is a mock of GroupStrategy interface.
type MockGroupStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockGroupStrategyMockRecorder
	isgomock struct{}
}

// MockGroupStrategyMockRecorder is the mock recorder for MockGroupStrategy.
type MockGroupStrategyMockRecorder struct {
	mock *MockGroupStrategy
}

// NewMockGroupStrategy creates a new mock instance.
func NewMockGroupStrategy(ctrl *gomock.Controller) *MockGroupStrategy {
	mock := &MockGroupStrategy{ctrl: ctrl}
	mock.recorder = &MockGroupStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGroupStrategy) EXPECT() *MockGroupStrategyMockRecorder {
	return m.recorder
}

// Exclusion mocks base method.
func (m *MockGroupStrategy) Exclusion(ctx context.Context, req *Request, edge *GroupEdge) (*Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exclusion", ctx, req, edge)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exclusion indicates an expected call of Exclusion.
func (mr *MockGroupStrategyMockRecorder) Exclusion(ctx, req, edge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exclusion", reflect.TypeOf((*MockGroupStrategy)(nil).Exclusion), ctx, req, edge)
}

// Intersection mocks base method.
func (m *MockGroupStrategy) Intersection(ctx context.Context, req *Request, edge *GroupEdge) (*Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Intersection", ctx, req, edge)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Intersection indicates an expected call of Intersection.
func (mr *MockGroupStrategyMockRecorder) Intersection(ctx, req, edge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Intersection", reflect.TypeOf((*MockGroupStrategy)(nil).Intersection), ctx, req, edge)
}

// Union mocks base method.
func (m *MockGroupStrategy) Union(ctx context.Context, req *Request, edge *GroupEdge) (*Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Union", ctx, req, edge)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Union indicates an expected call of Union.
func (mr *MockGroupStrategyMockRecorder) Union(ctx, req, edge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Union", reflect.TypeOf((*MockGroupStrategy)(nil).Union), ctx, req, edge)
}

// MockEdgeStrategy is a mock of EdgeStrategy interface.
type MockEdgeStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockEdgeStrategyMockRecorder
	isgomock struct{}
}

// MockEdgeStrategyMockRecorder is the mock recorder for MockEdgeStrategy.
type MockEdgeStrategyMockRecorder struct {
	mock *MockEdgeStrategy
}

// NewMockEdgeStrategy creates a new mock instance.
func NewMockEdgeStrategy(ctrl *gomock.Controller) *MockEdgeStrategy {
	mock := &MockEdgeStrategy{ctrl: ctrl}
	mock.recorder = &MockEdgeStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEdgeStrategy) EXPECT() *MockEdgeStrategyMockRecorder {
	return m.recorder
}

// TTU mocks base method.
func (m *MockEdgeStrategy) TTU(ctx context.Context, req *Request, edge *graph.WeightedAuthorizationModelEdge, iter storage.TupleKeyIterator, arg4 *sync.Map) (*Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TTU", ctx, req, edge, iter, arg4)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TTU indicates an expected call of TTU.
func (mr *MockEdgeStrategyMockRecorder) TTU(ctx, req, edge, iter, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TTU", reflect.TypeOf((*MockEdgeStrategy)(nil).TTU), ctx, req, edge, iter, arg4)
}

// Userset mocks base method.
func (m *MockEdgeStrategy) Userset(ctx context.Context, req *Request, edge *graph.WeightedAuthorizationModelEdge, iter storage.TupleKeyIterator, arg4 *sync.Map) (*Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Userset", ctx, req, edge, iter, arg4)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Userset indicates an expected call of Userset.
func (mr *MockEdgeStrategyMockRecorder) Userset(ctx, req, edge, iter, arg4 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Userset", reflect.TypeOf((*MockEdgeStrategy)(nil).Userset), ctx, req, edge, iter, arg4)
}
