@fga_api_url = https://authzen-interop.openfga.dev
@fga_store_id = 01JG9JGS4W0950VN17G8NNAH3C
@fga_api_key = <key>

# Simple Evaluation Request
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/evaluation
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

{
  "subject": {
    "type": "user",
    "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
  },
  "action": {
    "name": "can_read_user"
  },
  "resource": {
    "type": "user",
    "id": "beth@the-smiths.com"
 
  }
}

### Simple Evaluation Request with Invalid Type
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/evaluation
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

{
  "subject": {
    "type": "user",
    "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
  },
  "action": {
    "name": "can_read_user"
  },
  "resource": {
    "type": "usr",
    "id": "beth@the-smiths.com"
 
  }
}


### Batch EvaluationS request with invalid type
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/evaluations
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

 {
  "evaluations" : [
    {
      "subject": {
        "type": "user",
        "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
      },
      "action": {
        "name": "can_read_user"
      },
      "resource": {
        "type": "ser",
        "id": "rick@the-citadel.com"
      }
    },
    {
      "subject": {
        "type": "user",
        "id": "XiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
      },
      "action": {
        "name": "can_read_user"
      },
      "resource": {
        "type": "user",
        "id": "rick1@the-citadel.com"
      }
    }
  ]
}


### Batch EvaluationS request 
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/evaluations
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

 {
  "evaluations" : [
    {
      "subject": {
        "type": "user",
        "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
      },
      "action": {
        "name": "can_read_user"
      },
      "resource": {
        "type": "ser",
        "id": "rick@the-citadel.com"
      }
    },
    {
      "subject": {
        "type": "user",
        "id": "XiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
      },
      "action": {
        "name": "can_read_user"
      },
      "resource": {
        "type": "user",
        "id": "rick1@the-citadel.com"
      }
    }
  ]
}

