#### @fga_api_url =
@fga_api_url =  http://localhost:8080
@fga_store_id = 01KEVFH4WDFMFD2TA6CD05GM3S
@fga_model_id = YOUR_MODEL_ID_HERE

# =============================================================================
# NOTE: Authorization Model ID
# =============================================================================
# You can specify a specific authorization model ID using the header:
#   Openfga-Authorization-Model-Id: <model_id>
# If not specified, the latest model for the store is used.

# Simple Evaluation Request

POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/evaluation
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

{
  "subject": {
    "type": "user",
    "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
  },
  "action": {
    "name": "can_read_user"
  },
  "resource": {
    "type": "user",
    "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"

  }
}

### Evaluation Request with specific Authorization Model ID
# Using the Openfga-Authorization-Model-Id header to specify a model version

POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/evaluation
Content-Type: application/json
Authorization: bearer {{fga_api_key}}
Openfga-Authorization-Model-Id: {{fga_model_id}}

{
  "subject": {
    "type": "user",
    "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
  },
  "action": {
    "name": "can_read_user"
  },
  "resource": {
    "type": "user",
    "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
  }
}

### Batch EvaluationS request 
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/evaluations
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

 {
  "evaluations" : [
    {
      "subject": {
        "type": "user",
        "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
      },
      "action": {
        "name": "can_read_user"
      },
      "resource": {
        "type": "user",
        "id": "rick@the-citadel.com"
      }
    },
    {
      "subject": {
        "type": "user",
        "id": "XiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
      },
      "action": {
        "name": "can_read_user"
      },
      "resource": {
        "type": "user",
        "id": "rick1@the-citadel.com"
      }
    }
  ]
}


### Subject Search - Find users who can read a specific todo
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/search/subject
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

{
  "subject": {
    "type": "user"
  },
  "resource": {
    "type": "todo",
    "id": "7240d0db-8ff0-41ec-98b2-34a096273b93"
  },
  "action": {
    "name": "owner"
  },
  "page": {
    "limit": 10
  }
}

### Subject Search - Find users who can delete a specific todo item
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/search/subject
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

{
  "subject": {
    "type": "user"
  },
  "resource": {
    "type": "todo",
    "id": "todo-1"
  },
  "action": {
    "name": "can_delete_todo"
  }
}

### Resource Search - Find all todos a user can read
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/search/resource
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

{
  "subject": {
    "type": "user",
    "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
  },
  "action": {
    "name": "can_read_todos"
  },
  "resource": {
    "type": "todo"
  },
  "page": {
    "limit": 20
  }
}

### Resource Search - Find all todos a user can update
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/search/resource
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

{
  "subject": {
    "type": "user",
    "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
  },
  "action": {
    "name": "can_update_todo"
  },
  "resource": {
    "type": "todo"
  },
  "page": {
    "limit": 3
  }
}

### Action Search - Find all actions a user can perform on a todo
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/search/action
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

{
  "subject": {
    "type": "user",
    "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
  },
  "resource": {
    "type": "todo",
    "id": "1"
  }
}

### Action Search - Find all actions on a specific todo item
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/search/action
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

{
  "subject": {
    "type": "user",
    "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
  },
  "resource": {
    "type": "todo",
    "id": "todo-1"
  }
}

### PDP Metadata Discovery
GET {{fga_api_url}}/.well-known/authzen-configuration
Content-Type: application/json


### Stores

POST {{fga_api_url}}/stores/{{fga_store_id}}/read
Authorization: bearer {{fga_api_key}}
Content-Type: application/json

{
  "page_size": 100
}
### Stores

GET {{fga_api_url}}/stores
Authorization: bearer {{fga_api_key}}

Content-Type: application/json


