@fga_api_url = http://ec2-user@ec2-3-21-166-38.us-east-2.compute.amazonaws.com
@fga_api_key = FbtmrFbuBOT/4R68B2s0pSYsPg5BI6dr+b7KX1OGwhs=
@fga_store_id = 01JG2JKG07BQE6PAK8ZZWYQ4YK

# Simple Evaluation Request
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/evaluation
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

{
  "subject": {
    "type": "user",
    "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
  },
  "action": {
    "name": "can_read_user"
  },
  "resource": {
    "type": "user",
    "id": "beth@the-smiths.com"
 
  }
}

### Simple Evaluation Request with Invalid Type
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/evaluation
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

{
  "subject": {
    "type": "user",
    "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
  },
  "action": {
    "name": "can_read_user"
  },
  "resource": {
    "type": "usr",
    "id": "beth@the-smiths.com"
 
  }
}


### Batch EvaluationS request with invalid type
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/evaluations
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

 {
  "evaluations" : [
    {
      "subject": {
        "type": "user",
        "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
      },
      "action": {
        "name": "can_read_user"
      },
      "resource": {
        "type": "ser",
        "id": "rick@the-citadel.com"
      }
    },
    {
      "subject": {
        "type": "user",
        "id": "XiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
      },
      "action": {
        "name": "can_read_user"
      },
      "resource": {
        "type": "user",
        "id": "rick1@the-citadel.com"
      }
    }
  ]
}


### Batch EvaluationS request with invalid type
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/evaluations
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

 {
  "evaluations" : [
    {
      "subject": {
        "type": "user",
        "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
      },
      "action": {
        "name": "can_read_user"
      },
      "resource": {
        "type": "ser",
        "id": "rick@the-citadel.com"
      }
    },
    {
      "subject": {
        "type": "user",
        "id": "XiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
      },
      "action": {
        "name": "can_read_user"
      },
      "resource": {
        "type": "user",
        "id": "rick1@the-citadel.com"
      }
    }
  ]
}

### Batch EvaluationS request 
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/evaluations
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

 {
  "evaluations" : [
    {
      "subject": {
        "type": "user",
        "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
      },
      "action": {
        "name": "can_read_user"
      },
      "resource": {
        "type": "ser",
        "id": "rick@the-citadel.com"
      }
    },
    {
      "subject": {
        "type": "user",
        "id": "XiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
      },
      "action": {
        "name": "can_read_user"
      },
      "resource": {
        "type": "user",
        "id": "rick1@the-citadel.com"
      }
    }
  ]
}

### Create New Authorization Model
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/evaluation
Authorization: bearer {{fga_api_key}}
Content-Type: application/json

 {
  "subject": {
    "type": "user",
    "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
  },
  "action": {
    "name": "can_read_todos"
  },
  "resource": {
    "type": "todo",
    "id": "todo-1"
  }
}

### Query all tuples
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/evaluation
Authorization: bearer {{fga_api_key}}
Content-Type: application/json

{
  "subject": {
    "type": "user",
    "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
  },
  "action": {
    "name": "can_update_todo"
  },
  "resource": {
    "type": "todo",
    "id": "7240d0db-8ff0-41ec-98b2-34a096273b9f",
    "properties": {
      "ownerID": "rick@the-citadel.com"
    }
  }
}

###  
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/evaluation
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

{
  "subject": {
    "type": "user",
    "id": "CiRmZDA2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
  },
  "action": {
    "name": "can_update_todo"
  },
  "resource": {
    "type": "todo",
    "id": "7240d0db-8ff0-41ec-98b2-34a096273b9f",
    "properties": {
      "ownerID": "morty@the-citadel.com"
    }
  }
}


### Check
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/evaluation
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

 {
  "subject": {
    "type": "user",
    "id": "CiRmZDI2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
  },
  "action": {
    "name": "can_delete_todo"
  },
  "resource": {
    "type": "todo",
    "id": "7240d0db-8ff0-41ec-98b2-34a096273b9f",
    "properties": {
      "ownerID": "summer@the-citadel.com"
    }
  }
}

### Check with contextual tuples
POST {{fga_api_url}}/stores/{{fga_store_id}}/access/v1/evaluation
Content-Type: application/json
Authorization: bearer {{fga_api_key}}

 {
  "subject": {
    "type": "user",
    "id": "CiRmZDI2MTRkMy1jMzlhLTQ3ODEtYjdiZC04Yjk2ZjVhNTEwMGQSBWxvY2Fs"
  },
  "action": {
    "name": "can_update_todo"
  },
  "resource": {
    "type": "todo",
    "id": "7240d0db-8ff0-41ec-98b2-34a096273b9f",
    "properties": {
      "ownerID": "summer@the-citadel.com"
    }
  }
}
