// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: storage/v1/storage.proto

package storagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OnMissingDelete specifies behavior when attempting to delete a non-existent tuple.
type OnMissingDelete int32

const (
	OnMissingDelete_ON_MISSING_DELETE_ERROR  OnMissingDelete = 0 // Return an error
	OnMissingDelete_ON_MISSING_DELETE_IGNORE OnMissingDelete = 1 // Silently ignore (no-op)
)

// Enum value maps for OnMissingDelete.
var (
	OnMissingDelete_name = map[int32]string{
		0: "ON_MISSING_DELETE_ERROR",
		1: "ON_MISSING_DELETE_IGNORE",
	}
	OnMissingDelete_value = map[string]int32{
		"ON_MISSING_DELETE_ERROR":  0,
		"ON_MISSING_DELETE_IGNORE": 1,
	}
)

func (x OnMissingDelete) Enum() *OnMissingDelete {
	p := new(OnMissingDelete)
	*p = x
	return p
}

func (x OnMissingDelete) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnMissingDelete) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_v1_storage_proto_enumTypes[0].Descriptor()
}

func (OnMissingDelete) Type() protoreflect.EnumType {
	return &file_storage_v1_storage_proto_enumTypes[0]
}

func (x OnMissingDelete) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OnMissingDelete.Descriptor instead.
func (OnMissingDelete) EnumDescriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{0}
}

// OnDuplicateInsert specifies behavior when attempting to insert an existing tuple.
type OnDuplicateInsert int32

const (
	OnDuplicateInsert_ON_DUPLICATE_INSERT_ERROR  OnDuplicateInsert = 0 // Return an error
	OnDuplicateInsert_ON_DUPLICATE_INSERT_IGNORE OnDuplicateInsert = 1 // Silently ignore (no-op)
)

// Enum value maps for OnDuplicateInsert.
var (
	OnDuplicateInsert_name = map[int32]string{
		0: "ON_DUPLICATE_INSERT_ERROR",
		1: "ON_DUPLICATE_INSERT_IGNORE",
	}
	OnDuplicateInsert_value = map[string]int32{
		"ON_DUPLICATE_INSERT_ERROR":  0,
		"ON_DUPLICATE_INSERT_IGNORE": 1,
	}
)

func (x OnDuplicateInsert) Enum() *OnDuplicateInsert {
	p := new(OnDuplicateInsert)
	*p = x
	return p
}

func (x OnDuplicateInsert) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OnDuplicateInsert) Descriptor() protoreflect.EnumDescriptor {
	return file_storage_v1_storage_proto_enumTypes[1].Descriptor()
}

func (OnDuplicateInsert) Type() protoreflect.EnumType {
	return &file_storage_v1_storage_proto_enumTypes[1]
}

func (x OnDuplicateInsert) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OnDuplicateInsert.Descriptor instead.
func (OnDuplicateInsert) EnumDescriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{1}
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Filter        *ReadFilter            `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Consistency   *ConsistencyOptions    `protobuf:"bytes,3,opt,name=consistency,proto3" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{0}
}

func (x *ReadRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *ReadRequest) GetFilter() *ReadFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ReadRequest) GetConsistency() *ConsistencyOptions {
	if x != nil {
		return x.Consistency
	}
	return nil
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tuple         *Tuple                 `protobuf:"bytes,1,opt,name=tuple,proto3" json:"tuple,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{1}
}

func (x *ReadResponse) GetTuple() *Tuple {
	if x != nil {
		return x.Tuple
	}
	return nil
}

type ReadPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Filter        *ReadFilter            `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Pagination    *PaginationOptions     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Consistency   *ConsistencyOptions    `protobuf:"bytes,4,opt,name=consistency,proto3" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadPageRequest) Reset() {
	*x = ReadPageRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPageRequest) ProtoMessage() {}

func (x *ReadPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPageRequest.ProtoReflect.Descriptor instead.
func (*ReadPageRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{2}
}

func (x *ReadPageRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *ReadPageRequest) GetFilter() *ReadFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ReadPageRequest) GetPagination() *PaginationOptions {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ReadPageRequest) GetConsistency() *ConsistencyOptions {
	if x != nil {
		return x.Consistency
	}
	return nil
}

type ReadPageResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Tuples            []*Tuple               `protobuf:"bytes,1,rep,name=tuples,proto3" json:"tuples,omitempty"`
	ContinuationToken string                 `protobuf:"bytes,2,opt,name=continuation_token,json=continuationToken,proto3" json:"continuation_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReadPageResponse) Reset() {
	*x = ReadPageResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadPageResponse) ProtoMessage() {}

func (x *ReadPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadPageResponse.ProtoReflect.Descriptor instead.
func (*ReadPageResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{3}
}

func (x *ReadPageResponse) GetTuples() []*Tuple {
	if x != nil {
		return x.Tuples
	}
	return nil
}

func (x *ReadPageResponse) GetContinuationToken() string {
	if x != nil {
		return x.ContinuationToken
	}
	return ""
}

type ReadUserTupleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	TupleKey      *TupleKey              `protobuf:"bytes,2,opt,name=tuple_key,json=tupleKey,proto3" json:"tuple_key,omitempty"`
	Consistency   *ConsistencyOptions    `protobuf:"bytes,3,opt,name=consistency,proto3" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadUserTupleRequest) Reset() {
	*x = ReadUserTupleRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadUserTupleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadUserTupleRequest) ProtoMessage() {}

func (x *ReadUserTupleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadUserTupleRequest.ProtoReflect.Descriptor instead.
func (*ReadUserTupleRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{4}
}

func (x *ReadUserTupleRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *ReadUserTupleRequest) GetTupleKey() *TupleKey {
	if x != nil {
		return x.TupleKey
	}
	return nil
}

func (x *ReadUserTupleRequest) GetConsistency() *ConsistencyOptions {
	if x != nil {
		return x.Consistency
	}
	return nil
}

type ReadUserTupleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tuple         *Tuple                 `protobuf:"bytes,1,opt,name=tuple,proto3" json:"tuple,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadUserTupleResponse) Reset() {
	*x = ReadUserTupleResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadUserTupleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadUserTupleResponse) ProtoMessage() {}

func (x *ReadUserTupleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadUserTupleResponse.ProtoReflect.Descriptor instead.
func (*ReadUserTupleResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{5}
}

func (x *ReadUserTupleResponse) GetTuple() *Tuple {
	if x != nil {
		return x.Tuple
	}
	return nil
}

type ReadUsersetTuplesRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Store         string                   `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Filter        *ReadUsersetTuplesFilter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Consistency   *ConsistencyOptions      `protobuf:"bytes,3,opt,name=consistency,proto3" json:"consistency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadUsersetTuplesRequest) Reset() {
	*x = ReadUsersetTuplesRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadUsersetTuplesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadUsersetTuplesRequest) ProtoMessage() {}

func (x *ReadUsersetTuplesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadUsersetTuplesRequest.ProtoReflect.Descriptor instead.
func (*ReadUsersetTuplesRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{6}
}

func (x *ReadUsersetTuplesRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *ReadUsersetTuplesRequest) GetFilter() *ReadUsersetTuplesFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ReadUsersetTuplesRequest) GetConsistency() *ConsistencyOptions {
	if x != nil {
		return x.Consistency
	}
	return nil
}

type ReadUsersetTuplesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tuple         *Tuple                 `protobuf:"bytes,1,opt,name=tuple,proto3" json:"tuple,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadUsersetTuplesResponse) Reset() {
	*x = ReadUsersetTuplesResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadUsersetTuplesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadUsersetTuplesResponse) ProtoMessage() {}

func (x *ReadUsersetTuplesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadUsersetTuplesResponse.ProtoReflect.Descriptor instead.
func (*ReadUsersetTuplesResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{7}
}

func (x *ReadUsersetTuplesResponse) GetTuple() *Tuple {
	if x != nil {
		return x.Tuple
	}
	return nil
}

type ReadStartingWithUserRequest struct {
	state                      protoimpl.MessageState      `protogen:"open.v1"`
	Store                      string                      `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Filter                     *ReadStartingWithUserFilter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Consistency                *ConsistencyOptions         `protobuf:"bytes,3,opt,name=consistency,proto3" json:"consistency,omitempty"`
	WithResultsSortedAscending bool                        `protobuf:"varint,4,opt,name=with_results_sorted_ascending,json=withResultsSortedAscending,proto3" json:"with_results_sorted_ascending,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ReadStartingWithUserRequest) Reset() {
	*x = ReadStartingWithUserRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStartingWithUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStartingWithUserRequest) ProtoMessage() {}

func (x *ReadStartingWithUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStartingWithUserRequest.ProtoReflect.Descriptor instead.
func (*ReadStartingWithUserRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{8}
}

func (x *ReadStartingWithUserRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *ReadStartingWithUserRequest) GetFilter() *ReadStartingWithUserFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ReadStartingWithUserRequest) GetConsistency() *ConsistencyOptions {
	if x != nil {
		return x.Consistency
	}
	return nil
}

func (x *ReadStartingWithUserRequest) GetWithResultsSortedAscending() bool {
	if x != nil {
		return x.WithResultsSortedAscending
	}
	return false
}

type ReadStartingWithUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tuple         *Tuple                 `protobuf:"bytes,1,opt,name=tuple,proto3" json:"tuple,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStartingWithUserResponse) Reset() {
	*x = ReadStartingWithUserResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStartingWithUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStartingWithUserResponse) ProtoMessage() {}

func (x *ReadStartingWithUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStartingWithUserResponse.ProtoReflect.Descriptor instead.
func (*ReadStartingWithUserResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{9}
}

func (x *ReadStartingWithUserResponse) GetTuple() *Tuple {
	if x != nil {
		return x.Tuple
	}
	return nil
}

type WriteRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Store         string                      `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Deletes       []*TupleKeyWithoutCondition `protobuf:"bytes,2,rep,name=deletes,proto3" json:"deletes,omitempty"`
	Writes        []*TupleKey                 `protobuf:"bytes,3,rep,name=writes,proto3" json:"writes,omitempty"`
	Options       *TupleWriteOptions          `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{10}
}

func (x *WriteRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *WriteRequest) GetDeletes() []*TupleKeyWithoutCondition {
	if x != nil {
		return x.Deletes
	}
	return nil
}

func (x *WriteRequest) GetWrites() []*TupleKey {
	if x != nil {
		return x.Writes
	}
	return nil
}

func (x *WriteRequest) GetOptions() *TupleWriteOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{11}
}

type ReadAuthorizationModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAuthorizationModelRequest) Reset() {
	*x = ReadAuthorizationModelRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAuthorizationModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAuthorizationModelRequest) ProtoMessage() {}

func (x *ReadAuthorizationModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAuthorizationModelRequest.ProtoReflect.Descriptor instead.
func (*ReadAuthorizationModelRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{12}
}

func (x *ReadAuthorizationModelRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *ReadAuthorizationModelRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadAuthorizationModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *AuthorizationModel    `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAuthorizationModelResponse) Reset() {
	*x = ReadAuthorizationModelResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAuthorizationModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAuthorizationModelResponse) ProtoMessage() {}

func (x *ReadAuthorizationModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAuthorizationModelResponse.ProtoReflect.Descriptor instead.
func (*ReadAuthorizationModelResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{13}
}

func (x *ReadAuthorizationModelResponse) GetModel() *AuthorizationModel {
	if x != nil {
		return x.Model
	}
	return nil
}

type ReadAuthorizationModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Pagination    *PaginationOptions     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAuthorizationModelsRequest) Reset() {
	*x = ReadAuthorizationModelsRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAuthorizationModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAuthorizationModelsRequest) ProtoMessage() {}

func (x *ReadAuthorizationModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAuthorizationModelsRequest.ProtoReflect.Descriptor instead.
func (*ReadAuthorizationModelsRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{14}
}

func (x *ReadAuthorizationModelsRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *ReadAuthorizationModelsRequest) GetPagination() *PaginationOptions {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ReadAuthorizationModelsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Models            []*AuthorizationModel  `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	ContinuationToken string                 `protobuf:"bytes,2,opt,name=continuation_token,json=continuationToken,proto3" json:"continuation_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReadAuthorizationModelsResponse) Reset() {
	*x = ReadAuthorizationModelsResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAuthorizationModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAuthorizationModelsResponse) ProtoMessage() {}

func (x *ReadAuthorizationModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAuthorizationModelsResponse.ProtoReflect.Descriptor instead.
func (*ReadAuthorizationModelsResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{15}
}

func (x *ReadAuthorizationModelsResponse) GetModels() []*AuthorizationModel {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ReadAuthorizationModelsResponse) GetContinuationToken() string {
	if x != nil {
		return x.ContinuationToken
	}
	return ""
}

type FindLatestAuthorizationModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindLatestAuthorizationModelRequest) Reset() {
	*x = FindLatestAuthorizationModelRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindLatestAuthorizationModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindLatestAuthorizationModelRequest) ProtoMessage() {}

func (x *FindLatestAuthorizationModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindLatestAuthorizationModelRequest.ProtoReflect.Descriptor instead.
func (*FindLatestAuthorizationModelRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{16}
}

func (x *FindLatestAuthorizationModelRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

type FindLatestAuthorizationModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         *AuthorizationModel    `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindLatestAuthorizationModelResponse) Reset() {
	*x = FindLatestAuthorizationModelResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindLatestAuthorizationModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindLatestAuthorizationModelResponse) ProtoMessage() {}

func (x *FindLatestAuthorizationModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindLatestAuthorizationModelResponse.ProtoReflect.Descriptor instead.
func (*FindLatestAuthorizationModelResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{17}
}

func (x *FindLatestAuthorizationModelResponse) GetModel() *AuthorizationModel {
	if x != nil {
		return x.Model
	}
	return nil
}

type WriteAuthorizationModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Model         *AuthorizationModel    `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteAuthorizationModelRequest) Reset() {
	*x = WriteAuthorizationModelRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteAuthorizationModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteAuthorizationModelRequest) ProtoMessage() {}

func (x *WriteAuthorizationModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteAuthorizationModelRequest.ProtoReflect.Descriptor instead.
func (*WriteAuthorizationModelRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{18}
}

func (x *WriteAuthorizationModelRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *WriteAuthorizationModelRequest) GetModel() *AuthorizationModel {
	if x != nil {
		return x.Model
	}
	return nil
}

type WriteAuthorizationModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteAuthorizationModelResponse) Reset() {
	*x = WriteAuthorizationModelResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteAuthorizationModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteAuthorizationModelResponse) ProtoMessage() {}

func (x *WriteAuthorizationModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteAuthorizationModelResponse.ProtoReflect.Descriptor instead.
func (*WriteAuthorizationModelResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{19}
}

type CreateStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         *Store                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStoreRequest) Reset() {
	*x = CreateStoreRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoreRequest) ProtoMessage() {}

func (x *CreateStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoreRequest.ProtoReflect.Descriptor instead.
func (*CreateStoreRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{20}
}

func (x *CreateStoreRequest) GetStore() *Store {
	if x != nil {
		return x.Store
	}
	return nil
}

type CreateStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         *Store                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStoreResponse) Reset() {
	*x = CreateStoreResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStoreResponse) ProtoMessage() {}

func (x *CreateStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStoreResponse.ProtoReflect.Descriptor instead.
func (*CreateStoreResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{21}
}

func (x *CreateStoreResponse) GetStore() *Store {
	if x != nil {
		return x.Store
	}
	return nil
}

type DeleteStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStoreRequest) Reset() {
	*x = DeleteStoreRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStoreRequest) ProtoMessage() {}

func (x *DeleteStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStoreRequest.ProtoReflect.Descriptor instead.
func (*DeleteStoreRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteStoreRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStoreResponse) Reset() {
	*x = DeleteStoreResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStoreResponse) ProtoMessage() {}

func (x *DeleteStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStoreResponse.ProtoReflect.Descriptor instead.
func (*DeleteStoreResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{23}
}

type GetStoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreRequest) Reset() {
	*x = GetStoreRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreRequest) ProtoMessage() {}

func (x *GetStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreRequest.ProtoReflect.Descriptor instead.
func (*GetStoreRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{24}
}

func (x *GetStoreRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetStoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         *Store                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoreResponse) Reset() {
	*x = GetStoreResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoreResponse) ProtoMessage() {}

func (x *GetStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoreResponse.ProtoReflect.Descriptor instead.
func (*GetStoreResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{25}
}

func (x *GetStoreResponse) GetStore() *Store {
	if x != nil {
		return x.Store
	}
	return nil
}

type ListStoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pagination    *PaginationOptions     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStoresRequest) Reset() {
	*x = ListStoresRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoresRequest) ProtoMessage() {}

func (x *ListStoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoresRequest.ProtoReflect.Descriptor instead.
func (*ListStoresRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{26}
}

func (x *ListStoresRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListStoresRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListStoresRequest) GetPagination() *PaginationOptions {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListStoresResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Stores            []*Store               `protobuf:"bytes,1,rep,name=stores,proto3" json:"stores,omitempty"`
	ContinuationToken string                 `protobuf:"bytes,2,opt,name=continuation_token,json=continuationToken,proto3" json:"continuation_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListStoresResponse) Reset() {
	*x = ListStoresResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStoresResponse) ProtoMessage() {}

func (x *ListStoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStoresResponse.ProtoReflect.Descriptor instead.
func (*ListStoresResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{27}
}

func (x *ListStoresResponse) GetStores() []*Store {
	if x != nil {
		return x.Stores
	}
	return nil
}

func (x *ListStoresResponse) GetContinuationToken() string {
	if x != nil {
		return x.ContinuationToken
	}
	return ""
}

type WriteAssertionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Assertions    []*Assertion           `protobuf:"bytes,3,rep,name=assertions,proto3" json:"assertions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteAssertionsRequest) Reset() {
	*x = WriteAssertionsRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteAssertionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteAssertionsRequest) ProtoMessage() {}

func (x *WriteAssertionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteAssertionsRequest.ProtoReflect.Descriptor instead.
func (*WriteAssertionsRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{28}
}

func (x *WriteAssertionsRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *WriteAssertionsRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *WriteAssertionsRequest) GetAssertions() []*Assertion {
	if x != nil {
		return x.Assertions
	}
	return nil
}

type WriteAssertionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteAssertionsResponse) Reset() {
	*x = WriteAssertionsResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteAssertionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteAssertionsResponse) ProtoMessage() {}

func (x *WriteAssertionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteAssertionsResponse.ProtoReflect.Descriptor instead.
func (*WriteAssertionsResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{29}
}

type ReadAssertionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAssertionsRequest) Reset() {
	*x = ReadAssertionsRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAssertionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAssertionsRequest) ProtoMessage() {}

func (x *ReadAssertionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAssertionsRequest.ProtoReflect.Descriptor instead.
func (*ReadAssertionsRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{30}
}

func (x *ReadAssertionsRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *ReadAssertionsRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type ReadAssertionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assertions    []*Assertion           `protobuf:"bytes,1,rep,name=assertions,proto3" json:"assertions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadAssertionsResponse) Reset() {
	*x = ReadAssertionsResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadAssertionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadAssertionsResponse) ProtoMessage() {}

func (x *ReadAssertionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadAssertionsResponse.ProtoReflect.Descriptor instead.
func (*ReadAssertionsResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{31}
}

func (x *ReadAssertionsResponse) GetAssertions() []*Assertion {
	if x != nil {
		return x.Assertions
	}
	return nil
}

type ReadChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Store         string                 `protobuf:"bytes,1,opt,name=store,proto3" json:"store,omitempty"`
	Filter        *ReadChangesFilter     `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Pagination    *PaginationOptions     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	SortDesc      bool                   `protobuf:"varint,4,opt,name=sort_desc,json=sortDesc,proto3" json:"sort_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadChangesRequest) Reset() {
	*x = ReadChangesRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChangesRequest) ProtoMessage() {}

func (x *ReadChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChangesRequest.ProtoReflect.Descriptor instead.
func (*ReadChangesRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{32}
}

func (x *ReadChangesRequest) GetStore() string {
	if x != nil {
		return x.Store
	}
	return ""
}

func (x *ReadChangesRequest) GetFilter() *ReadChangesFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ReadChangesRequest) GetPagination() *PaginationOptions {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ReadChangesRequest) GetSortDesc() bool {
	if x != nil {
		return x.SortDesc
	}
	return false
}

type ReadChangesResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Changes           []*TupleChange         `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	ContinuationToken string                 `protobuf:"bytes,2,opt,name=continuation_token,json=continuationToken,proto3" json:"continuation_token,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReadChangesResponse) Reset() {
	*x = ReadChangesResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChangesResponse) ProtoMessage() {}

func (x *ReadChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChangesResponse.ProtoReflect.Descriptor instead.
func (*ReadChangesResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{33}
}

func (x *ReadChangesResponse) GetChanges() []*TupleChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *ReadChangesResponse) GetContinuationToken() string {
	if x != nil {
		return x.ContinuationToken
	}
	return ""
}

type IsReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsReadyRequest) Reset() {
	*x = IsReadyRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsReadyRequest) ProtoMessage() {}

func (x *IsReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsReadyRequest.ProtoReflect.Descriptor instead.
func (*IsReadyRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{34}
}

type IsReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	IsReady       bool                   `protobuf:"varint,2,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsReadyResponse) Reset() {
	*x = IsReadyResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsReadyResponse) ProtoMessage() {}

func (x *IsReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsReadyResponse.ProtoReflect.Descriptor instead.
func (*IsReadyResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{35}
}

func (x *IsReadyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *IsReadyResponse) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

type MaxTuplesPerWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaxTuplesPerWriteRequest) Reset() {
	*x = MaxTuplesPerWriteRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxTuplesPerWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxTuplesPerWriteRequest) ProtoMessage() {}

func (x *MaxTuplesPerWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxTuplesPerWriteRequest.ProtoReflect.Descriptor instead.
func (*MaxTuplesPerWriteRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{36}
}

type MaxTuplesPerWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Max           int32                  `protobuf:"varint,1,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaxTuplesPerWriteResponse) Reset() {
	*x = MaxTuplesPerWriteResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxTuplesPerWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxTuplesPerWriteResponse) ProtoMessage() {}

func (x *MaxTuplesPerWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxTuplesPerWriteResponse.ProtoReflect.Descriptor instead.
func (*MaxTuplesPerWriteResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{37}
}

func (x *MaxTuplesPerWriteResponse) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type MaxTypesPerAuthorizationModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaxTypesPerAuthorizationModelRequest) Reset() {
	*x = MaxTypesPerAuthorizationModelRequest{}
	mi := &file_storage_v1_storage_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxTypesPerAuthorizationModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxTypesPerAuthorizationModelRequest) ProtoMessage() {}

func (x *MaxTypesPerAuthorizationModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxTypesPerAuthorizationModelRequest.ProtoReflect.Descriptor instead.
func (*MaxTypesPerAuthorizationModelRequest) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{38}
}

type MaxTypesPerAuthorizationModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Max           int32                  `protobuf:"varint,1,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaxTypesPerAuthorizationModelResponse) Reset() {
	*x = MaxTypesPerAuthorizationModelResponse{}
	mi := &file_storage_v1_storage_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaxTypesPerAuthorizationModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaxTypesPerAuthorizationModelResponse) ProtoMessage() {}

func (x *MaxTypesPerAuthorizationModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaxTypesPerAuthorizationModelResponse.ProtoReflect.Descriptor instead.
func (*MaxTypesPerAuthorizationModelResponse) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{39}
}

func (x *MaxTypesPerAuthorizationModelResponse) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

// ReadFilter specifies filter criteria for reading tuples.
// Empty strings act as wildcards (match any value).
type ReadFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object filters by object ID. Empty string matches any object.
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// relation filters by relation name. Empty string matches any relation.
	Relation string `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	// user filters by user or userset. Empty string matches any user.
	User string `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	// conditions filters by condition names. Empty list matches any condition.
	// Can include empty string to match tuples without conditions.
	Conditions    []string `protobuf:"bytes,4,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFilter) Reset() {
	*x = ReadFilter{}
	mi := &file_storage_v1_storage_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFilter) ProtoMessage() {}

func (x *ReadFilter) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFilter.ProtoReflect.Descriptor instead.
func (*ReadFilter) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{40}
}

func (x *ReadFilter) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ReadFilter) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *ReadFilter) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ReadFilter) GetConditions() []string {
	if x != nil {
		return x.Conditions
	}
	return nil
}

// ReadUsersetTuplesFilter specifies filter criteria for reading userset tuples.
type ReadUsersetTuplesFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object is the object to query (required).
	Object string `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	// relation is the relation to query (required).
	Relation string `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	// allowed_user_type_restrictions filters results to only these user types.
	// Empty list returns all userset tuples.
	AllowedUserTypeRestrictions []*RelationReference `protobuf:"bytes,3,rep,name=allowed_user_type_restrictions,json=allowedUserTypeRestrictions,proto3" json:"allowed_user_type_restrictions,omitempty"`
	// conditions filters by condition names.
	Conditions    []string `protobuf:"bytes,4,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadUsersetTuplesFilter) Reset() {
	*x = ReadUsersetTuplesFilter{}
	mi := &file_storage_v1_storage_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadUsersetTuplesFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadUsersetTuplesFilter) ProtoMessage() {}

func (x *ReadUsersetTuplesFilter) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadUsersetTuplesFilter.ProtoReflect.Descriptor instead.
func (*ReadUsersetTuplesFilter) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{41}
}

func (x *ReadUsersetTuplesFilter) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ReadUsersetTuplesFilter) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *ReadUsersetTuplesFilter) GetAllowedUserTypeRestrictions() []*RelationReference {
	if x != nil {
		return x.AllowedUserTypeRestrictions
	}
	return nil
}

func (x *ReadUsersetTuplesFilter) GetConditions() []string {
	if x != nil {
		return x.Conditions
	}
	return nil
}

// ReadStartingWithUserFilter specifies criteria for reverse reads starting from users.
type ReadStartingWithUserFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object_type is the type of objects to return (required).
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// relation is the relation to check (required).
	Relation string `protobuf:"bytes,2,opt,name=relation,proto3" json:"relation,omitempty"`
	// user_filter specifies the users/usersets to start from (required).
	UserFilter []*ObjectRelation `protobuf:"bytes,3,rep,name=user_filter,json=userFilter,proto3" json:"user_filter,omitempty"`
	// object_ids restricts results to specific object IDs.
	// Empty list returns results for all objects.
	// When provided, must be sorted in ascending order.
	ObjectIds []string `protobuf:"bytes,4,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	// conditions filters by condition names.
	Conditions    []string `protobuf:"bytes,5,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStartingWithUserFilter) Reset() {
	*x = ReadStartingWithUserFilter{}
	mi := &file_storage_v1_storage_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStartingWithUserFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStartingWithUserFilter) ProtoMessage() {}

func (x *ReadStartingWithUserFilter) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStartingWithUserFilter.ProtoReflect.Descriptor instead.
func (*ReadStartingWithUserFilter) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{42}
}

func (x *ReadStartingWithUserFilter) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *ReadStartingWithUserFilter) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *ReadStartingWithUserFilter) GetUserFilter() []*ObjectRelation {
	if x != nil {
		return x.UserFilter
	}
	return nil
}

func (x *ReadStartingWithUserFilter) GetObjectIds() []string {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

func (x *ReadStartingWithUserFilter) GetConditions() []string {
	if x != nil {
		return x.Conditions
	}
	return nil
}

// ReadChangesFilter specifies filter criteria for reading changelog entries.
type ReadChangesFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object_type filters changes to a specific object type.
	// Empty string returns changes for all object types.
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// horizon_offset_ms specifies how far back to read changes (in milliseconds).
	// Changes older than this offset are excluded.
	HorizonOffsetMs int64 `protobuf:"varint,2,opt,name=horizon_offset_ms,json=horizonOffsetMs,proto3" json:"horizon_offset_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReadChangesFilter) Reset() {
	*x = ReadChangesFilter{}
	mi := &file_storage_v1_storage_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadChangesFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadChangesFilter) ProtoMessage() {}

func (x *ReadChangesFilter) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadChangesFilter.ProtoReflect.Descriptor instead.
func (*ReadChangesFilter) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{43}
}

func (x *ReadChangesFilter) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *ReadChangesFilter) GetHorizonOffsetMs() int64 {
	if x != nil {
		return x.HorizonOffsetMs
	}
	return 0
}

// PaginationOptions controls pagination behavior.
type PaginationOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// page_size is the maximum number of items to return per page.
	// Must be greater than 0. Default is determined by the storage backend.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// from is a continuation token from a previous response.
	// Empty string starts from the beginning.
	From          string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationOptions) Reset() {
	*x = PaginationOptions{}
	mi := &file_storage_v1_storage_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationOptions) ProtoMessage() {}

func (x *PaginationOptions) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationOptions.ProtoReflect.Descriptor instead.
func (*PaginationOptions) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{44}
}

func (x *PaginationOptions) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationOptions) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

// ConsistencyOptions specifies the desired consistency level.
type ConsistencyOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// preference allows trading off between latency and consistency.
	Preference    ConsistencyPreference `protobuf:"varint,1,opt,name=preference,proto3,enum=storage.v1.types.ConsistencyPreference" json:"preference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsistencyOptions) Reset() {
	*x = ConsistencyOptions{}
	mi := &file_storage_v1_storage_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsistencyOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsistencyOptions) ProtoMessage() {}

func (x *ConsistencyOptions) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsistencyOptions.ProtoReflect.Descriptor instead.
func (*ConsistencyOptions) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{45}
}

func (x *ConsistencyOptions) GetPreference() ConsistencyPreference {
	if x != nil {
		return x.Preference
	}
	return ConsistencyPreference_CONSISTENCY_PREFERENCE_UNSPECIFIED
}

// TupleWriteOptions configures behavior for write operations.
type TupleWriteOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// on_missing_delete specifies behavior when deleting a non-existent tuple.
	OnMissingDelete OnMissingDelete `protobuf:"varint,1,opt,name=on_missing_delete,json=onMissingDelete,proto3,enum=storage.v1.OnMissingDelete" json:"on_missing_delete,omitempty"`
	// on_duplicate_insert specifies behavior when inserting an existing tuple.
	OnDuplicateInsert OnDuplicateInsert `protobuf:"varint,2,opt,name=on_duplicate_insert,json=onDuplicateInsert,proto3,enum=storage.v1.OnDuplicateInsert" json:"on_duplicate_insert,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TupleWriteOptions) Reset() {
	*x = TupleWriteOptions{}
	mi := &file_storage_v1_storage_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TupleWriteOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TupleWriteOptions) ProtoMessage() {}

func (x *TupleWriteOptions) ProtoReflect() protoreflect.Message {
	mi := &file_storage_v1_storage_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TupleWriteOptions.ProtoReflect.Descriptor instead.
func (*TupleWriteOptions) Descriptor() ([]byte, []int) {
	return file_storage_v1_storage_proto_rawDescGZIP(), []int{46}
}

func (x *TupleWriteOptions) GetOnMissingDelete() OnMissingDelete {
	if x != nil {
		return x.OnMissingDelete
	}
	return OnMissingDelete_ON_MISSING_DELETE_ERROR
}

func (x *TupleWriteOptions) GetOnDuplicateInsert() OnDuplicateInsert {
	if x != nil {
		return x.OnDuplicateInsert
	}
	return OnDuplicateInsert_ON_DUPLICATE_INSERT_ERROR
}

var File_storage_v1_storage_proto protoreflect.FileDescriptor

const file_storage_v1_storage_proto_rawDesc = "" +
	"\n" +
	"\x18storage/v1/storage.proto\x12\n" +
	"storage.v1\x1a\x1estorage/v1/openfga_types.proto\"\x95\x01\n" +
	"\vReadRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12.\n" +
	"\x06filter\x18\x02 \x01(\v2\x16.storage.v1.ReadFilterR\x06filter\x12@\n" +
	"\vconsistency\x18\x03 \x01(\v2\x1e.storage.v1.ConsistencyOptionsR\vconsistency\"=\n" +
	"\fReadResponse\x12-\n" +
	"\x05tuple\x18\x01 \x01(\v2\x17.storage.v1.types.TupleR\x05tuple\"\xd8\x01\n" +
	"\x0fReadPageRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12.\n" +
	"\x06filter\x18\x02 \x01(\v2\x16.storage.v1.ReadFilterR\x06filter\x12=\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1d.storage.v1.PaginationOptionsR\n" +
	"pagination\x12@\n" +
	"\vconsistency\x18\x04 \x01(\v2\x1e.storage.v1.ConsistencyOptionsR\vconsistency\"r\n" +
	"\x10ReadPageResponse\x12/\n" +
	"\x06tuples\x18\x01 \x03(\v2\x17.storage.v1.types.TupleR\x06tuples\x12-\n" +
	"\x12continuation_token\x18\x02 \x01(\tR\x11continuationToken\"\xa7\x01\n" +
	"\x14ReadUserTupleRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x127\n" +
	"\ttuple_key\x18\x02 \x01(\v2\x1a.storage.v1.types.TupleKeyR\btupleKey\x12@\n" +
	"\vconsistency\x18\x03 \x01(\v2\x1e.storage.v1.ConsistencyOptionsR\vconsistency\"F\n" +
	"\x15ReadUserTupleResponse\x12-\n" +
	"\x05tuple\x18\x01 \x01(\v2\x17.storage.v1.types.TupleR\x05tuple\"\xaf\x01\n" +
	"\x18ReadUsersetTuplesRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12;\n" +
	"\x06filter\x18\x02 \x01(\v2#.storage.v1.ReadUsersetTuplesFilterR\x06filter\x12@\n" +
	"\vconsistency\x18\x03 \x01(\v2\x1e.storage.v1.ConsistencyOptionsR\vconsistency\"J\n" +
	"\x19ReadUsersetTuplesResponse\x12-\n" +
	"\x05tuple\x18\x01 \x01(\v2\x17.storage.v1.types.TupleR\x05tuple\"\xf8\x01\n" +
	"\x1bReadStartingWithUserRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12>\n" +
	"\x06filter\x18\x02 \x01(\v2&.storage.v1.ReadStartingWithUserFilterR\x06filter\x12@\n" +
	"\vconsistency\x18\x03 \x01(\v2\x1e.storage.v1.ConsistencyOptionsR\vconsistency\x12A\n" +
	"\x1dwith_results_sorted_ascending\x18\x04 \x01(\bR\x1awithResultsSortedAscending\"M\n" +
	"\x1cReadStartingWithUserResponse\x12-\n" +
	"\x05tuple\x18\x01 \x01(\v2\x17.storage.v1.types.TupleR\x05tuple\"\xd7\x01\n" +
	"\fWriteRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12D\n" +
	"\adeletes\x18\x02 \x03(\v2*.storage.v1.types.TupleKeyWithoutConditionR\adeletes\x122\n" +
	"\x06writes\x18\x03 \x03(\v2\x1a.storage.v1.types.TupleKeyR\x06writes\x127\n" +
	"\aoptions\x18\x04 \x01(\v2\x1d.storage.v1.TupleWriteOptionsR\aoptions\"\x0f\n" +
	"\rWriteResponse\"E\n" +
	"\x1dReadAuthorizationModelRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\\\n" +
	"\x1eReadAuthorizationModelResponse\x12:\n" +
	"\x05model\x18\x01 \x01(\v2$.storage.v1.types.AuthorizationModelR\x05model\"u\n" +
	"\x1eReadAuthorizationModelsRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12=\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1d.storage.v1.PaginationOptionsR\n" +
	"pagination\"\x8e\x01\n" +
	"\x1fReadAuthorizationModelsResponse\x12<\n" +
	"\x06models\x18\x01 \x03(\v2$.storage.v1.types.AuthorizationModelR\x06models\x12-\n" +
	"\x12continuation_token\x18\x02 \x01(\tR\x11continuationToken\";\n" +
	"#FindLatestAuthorizationModelRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\"b\n" +
	"$FindLatestAuthorizationModelResponse\x12:\n" +
	"\x05model\x18\x01 \x01(\v2$.storage.v1.types.AuthorizationModelR\x05model\"r\n" +
	"\x1eWriteAuthorizationModelRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12:\n" +
	"\x05model\x18\x02 \x01(\v2$.storage.v1.types.AuthorizationModelR\x05model\"!\n" +
	"\x1fWriteAuthorizationModelResponse\"C\n" +
	"\x12CreateStoreRequest\x12-\n" +
	"\x05store\x18\x01 \x01(\v2\x17.storage.v1.types.StoreR\x05store\"D\n" +
	"\x13CreateStoreResponse\x12-\n" +
	"\x05store\x18\x01 \x01(\v2\x17.storage.v1.types.StoreR\x05store\"$\n" +
	"\x12DeleteStoreRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteStoreResponse\"!\n" +
	"\x0fGetStoreRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\x10GetStoreResponse\x12-\n" +
	"\x05store\x18\x01 \x01(\v2\x17.storage.v1.types.StoreR\x05store\"x\n" +
	"\x11ListStoresRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12=\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1d.storage.v1.PaginationOptionsR\n" +
	"pagination\"t\n" +
	"\x12ListStoresResponse\x12/\n" +
	"\x06stores\x18\x01 \x03(\v2\x17.storage.v1.types.StoreR\x06stores\x12-\n" +
	"\x12continuation_token\x18\x02 \x01(\tR\x11continuationToken\"\x86\x01\n" +
	"\x16WriteAssertionsRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12;\n" +
	"\n" +
	"assertions\x18\x03 \x03(\v2\x1b.storage.v1.types.AssertionR\n" +
	"assertions\"\x19\n" +
	"\x17WriteAssertionsResponse\"H\n" +
	"\x15ReadAssertionsRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\"U\n" +
	"\x16ReadAssertionsResponse\x12;\n" +
	"\n" +
	"assertions\x18\x01 \x03(\v2\x1b.storage.v1.types.AssertionR\n" +
	"assertions\"\xbd\x01\n" +
	"\x12ReadChangesRequest\x12\x14\n" +
	"\x05store\x18\x01 \x01(\tR\x05store\x125\n" +
	"\x06filter\x18\x02 \x01(\v2\x1d.storage.v1.ReadChangesFilterR\x06filter\x12=\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x1d.storage.v1.PaginationOptionsR\n" +
	"pagination\x12\x1b\n" +
	"\tsort_desc\x18\x04 \x01(\bR\bsortDesc\"}\n" +
	"\x13ReadChangesResponse\x127\n" +
	"\achanges\x18\x01 \x03(\v2\x1d.storage.v1.types.TupleChangeR\achanges\x12-\n" +
	"\x12continuation_token\x18\x02 \x01(\tR\x11continuationToken\"\x10\n" +
	"\x0eIsReadyRequest\"F\n" +
	"\x0fIsReadyResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x19\n" +
	"\bis_ready\x18\x02 \x01(\bR\aisReady\"\x1a\n" +
	"\x18MaxTuplesPerWriteRequest\"-\n" +
	"\x19MaxTuplesPerWriteResponse\x12\x10\n" +
	"\x03max\x18\x01 \x01(\x05R\x03max\"&\n" +
	"$MaxTypesPerAuthorizationModelRequest\"9\n" +
	"%MaxTypesPerAuthorizationModelResponse\x12\x10\n" +
	"\x03max\x18\x01 \x01(\x05R\x03max\"t\n" +
	"\n" +
	"ReadFilter\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x1e\n" +
	"\n" +
	"conditions\x18\x04 \x03(\tR\n" +
	"conditions\"\xd7\x01\n" +
	"\x17ReadUsersetTuplesFilter\x12\x16\n" +
	"\x06object\x18\x01 \x01(\tR\x06object\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\x12h\n" +
	"\x1eallowed_user_type_restrictions\x18\x03 \x03(\v2#.storage.v1.types.RelationReferenceR\x1ballowedUserTypeRestrictions\x12\x1e\n" +
	"\n" +
	"conditions\x18\x04 \x03(\tR\n" +
	"conditions\"\xdb\x01\n" +
	"\x1aReadStartingWithUserFilter\x12\x1f\n" +
	"\vobject_type\x18\x01 \x01(\tR\n" +
	"objectType\x12\x1a\n" +
	"\brelation\x18\x02 \x01(\tR\brelation\x12A\n" +
	"\vuser_filter\x18\x03 \x03(\v2 .storage.v1.types.ObjectRelationR\n" +
	"userFilter\x12\x1d\n" +
	"\n" +
	"object_ids\x18\x04 \x03(\tR\tobjectIds\x12\x1e\n" +
	"\n" +
	"conditions\x18\x05 \x03(\tR\n" +
	"conditions\"`\n" +
	"\x11ReadChangesFilter\x12\x1f\n" +
	"\vobject_type\x18\x01 \x01(\tR\n" +
	"objectType\x12*\n" +
	"\x11horizon_offset_ms\x18\x02 \x01(\x03R\x0fhorizonOffsetMs\"D\n" +
	"\x11PaginationOptions\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\"]\n" +
	"\x12ConsistencyOptions\x12G\n" +
	"\n" +
	"preference\x18\x01 \x01(\x0e2'.storage.v1.types.ConsistencyPreferenceR\n" +
	"preference\"\xab\x01\n" +
	"\x11TupleWriteOptions\x12G\n" +
	"\x11on_missing_delete\x18\x01 \x01(\x0e2\x1b.storage.v1.OnMissingDeleteR\x0fonMissingDelete\x12M\n" +
	"\x13on_duplicate_insert\x18\x02 \x01(\x0e2\x1d.storage.v1.OnDuplicateInsertR\x11onDuplicateInsert*L\n" +
	"\x0fOnMissingDelete\x12\x1b\n" +
	"\x17ON_MISSING_DELETE_ERROR\x10\x00\x12\x1c\n" +
	"\x18ON_MISSING_DELETE_IGNORE\x10\x01*R\n" +
	"\x11OnDuplicateInsert\x12\x1d\n" +
	"\x19ON_DUPLICATE_INSERT_ERROR\x10\x00\x12\x1e\n" +
	"\x1aON_DUPLICATE_INSERT_IGNORE\x10\x012\xbc\x0e\n" +
	"\x0eStorageService\x12;\n" +
	"\x04Read\x12\x17.storage.v1.ReadRequest\x1a\x18.storage.v1.ReadResponse0\x01\x12E\n" +
	"\bReadPage\x12\x1b.storage.v1.ReadPageRequest\x1a\x1c.storage.v1.ReadPageResponse\x12T\n" +
	"\rReadUserTuple\x12 .storage.v1.ReadUserTupleRequest\x1a!.storage.v1.ReadUserTupleResponse\x12b\n" +
	"\x11ReadUsersetTuples\x12$.storage.v1.ReadUsersetTuplesRequest\x1a%.storage.v1.ReadUsersetTuplesResponse0\x01\x12k\n" +
	"\x14ReadStartingWithUser\x12'.storage.v1.ReadStartingWithUserRequest\x1a(.storage.v1.ReadStartingWithUserResponse0\x01\x12<\n" +
	"\x05Write\x12\x18.storage.v1.WriteRequest\x1a\x19.storage.v1.WriteResponse\x12o\n" +
	"\x16ReadAuthorizationModel\x12).storage.v1.ReadAuthorizationModelRequest\x1a*.storage.v1.ReadAuthorizationModelResponse\x12r\n" +
	"\x17ReadAuthorizationModels\x12*.storage.v1.ReadAuthorizationModelsRequest\x1a+.storage.v1.ReadAuthorizationModelsResponse\x12\x81\x01\n" +
	"\x1cFindLatestAuthorizationModel\x12/.storage.v1.FindLatestAuthorizationModelRequest\x1a0.storage.v1.FindLatestAuthorizationModelResponse\x12r\n" +
	"\x17WriteAuthorizationModel\x12*.storage.v1.WriteAuthorizationModelRequest\x1a+.storage.v1.WriteAuthorizationModelResponse\x12N\n" +
	"\vCreateStore\x12\x1e.storage.v1.CreateStoreRequest\x1a\x1f.storage.v1.CreateStoreResponse\x12N\n" +
	"\vDeleteStore\x12\x1e.storage.v1.DeleteStoreRequest\x1a\x1f.storage.v1.DeleteStoreResponse\x12E\n" +
	"\bGetStore\x12\x1b.storage.v1.GetStoreRequest\x1a\x1c.storage.v1.GetStoreResponse\x12K\n" +
	"\n" +
	"ListStores\x12\x1d.storage.v1.ListStoresRequest\x1a\x1e.storage.v1.ListStoresResponse\x12Z\n" +
	"\x0fWriteAssertions\x12\".storage.v1.WriteAssertionsRequest\x1a#.storage.v1.WriteAssertionsResponse\x12W\n" +
	"\x0eReadAssertions\x12!.storage.v1.ReadAssertionsRequest\x1a\".storage.v1.ReadAssertionsResponse\x12N\n" +
	"\vReadChanges\x12\x1e.storage.v1.ReadChangesRequest\x1a\x1f.storage.v1.ReadChangesResponse\x12B\n" +
	"\aIsReady\x12\x1a.storage.v1.IsReadyRequest\x1a\x1b.storage.v1.IsReadyResponse\x12`\n" +
	"\x11MaxTuplesPerWrite\x12$.storage.v1.MaxTuplesPerWriteRequest\x1a%.storage.v1.MaxTuplesPerWriteResponse\x12\x84\x01\n" +
	"\x1dMaxTypesPerAuthorizationModel\x120.storage.v1.MaxTypesPerAuthorizationModelRequest\x1a1.storage.v1.MaxTypesPerAuthorizationModelResponseBHZFgithub.com/openfga/openfga/pkg/storage/grpc/proto/storage/v1;storagev1b\x06proto3"

var (
	file_storage_v1_storage_proto_rawDescOnce sync.Once
	file_storage_v1_storage_proto_rawDescData []byte
)

func file_storage_v1_storage_proto_rawDescGZIP() []byte {
	file_storage_v1_storage_proto_rawDescOnce.Do(func() {
		file_storage_v1_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_v1_storage_proto_rawDesc), len(file_storage_v1_storage_proto_rawDesc)))
	})
	return file_storage_v1_storage_proto_rawDescData
}

var file_storage_v1_storage_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_storage_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 47)
var file_storage_v1_storage_proto_goTypes = []any{
	(OnMissingDelete)(0),                          // 0: storage.v1.OnMissingDelete
	(OnDuplicateInsert)(0),                        // 1: storage.v1.OnDuplicateInsert
	(*ReadRequest)(nil),                           // 2: storage.v1.ReadRequest
	(*ReadResponse)(nil),                          // 3: storage.v1.ReadResponse
	(*ReadPageRequest)(nil),                       // 4: storage.v1.ReadPageRequest
	(*ReadPageResponse)(nil),                      // 5: storage.v1.ReadPageResponse
	(*ReadUserTupleRequest)(nil),                  // 6: storage.v1.ReadUserTupleRequest
	(*ReadUserTupleResponse)(nil),                 // 7: storage.v1.ReadUserTupleResponse
	(*ReadUsersetTuplesRequest)(nil),              // 8: storage.v1.ReadUsersetTuplesRequest
	(*ReadUsersetTuplesResponse)(nil),             // 9: storage.v1.ReadUsersetTuplesResponse
	(*ReadStartingWithUserRequest)(nil),           // 10: storage.v1.ReadStartingWithUserRequest
	(*ReadStartingWithUserResponse)(nil),          // 11: storage.v1.ReadStartingWithUserResponse
	(*WriteRequest)(nil),                          // 12: storage.v1.WriteRequest
	(*WriteResponse)(nil),                         // 13: storage.v1.WriteResponse
	(*ReadAuthorizationModelRequest)(nil),         // 14: storage.v1.ReadAuthorizationModelRequest
	(*ReadAuthorizationModelResponse)(nil),        // 15: storage.v1.ReadAuthorizationModelResponse
	(*ReadAuthorizationModelsRequest)(nil),        // 16: storage.v1.ReadAuthorizationModelsRequest
	(*ReadAuthorizationModelsResponse)(nil),       // 17: storage.v1.ReadAuthorizationModelsResponse
	(*FindLatestAuthorizationModelRequest)(nil),   // 18: storage.v1.FindLatestAuthorizationModelRequest
	(*FindLatestAuthorizationModelResponse)(nil),  // 19: storage.v1.FindLatestAuthorizationModelResponse
	(*WriteAuthorizationModelRequest)(nil),        // 20: storage.v1.WriteAuthorizationModelRequest
	(*WriteAuthorizationModelResponse)(nil),       // 21: storage.v1.WriteAuthorizationModelResponse
	(*CreateStoreRequest)(nil),                    // 22: storage.v1.CreateStoreRequest
	(*CreateStoreResponse)(nil),                   // 23: storage.v1.CreateStoreResponse
	(*DeleteStoreRequest)(nil),                    // 24: storage.v1.DeleteStoreRequest
	(*DeleteStoreResponse)(nil),                   // 25: storage.v1.DeleteStoreResponse
	(*GetStoreRequest)(nil),                       // 26: storage.v1.GetStoreRequest
	(*GetStoreResponse)(nil),                      // 27: storage.v1.GetStoreResponse
	(*ListStoresRequest)(nil),                     // 28: storage.v1.ListStoresRequest
	(*ListStoresResponse)(nil),                    // 29: storage.v1.ListStoresResponse
	(*WriteAssertionsRequest)(nil),                // 30: storage.v1.WriteAssertionsRequest
	(*WriteAssertionsResponse)(nil),               // 31: storage.v1.WriteAssertionsResponse
	(*ReadAssertionsRequest)(nil),                 // 32: storage.v1.ReadAssertionsRequest
	(*ReadAssertionsResponse)(nil),                // 33: storage.v1.ReadAssertionsResponse
	(*ReadChangesRequest)(nil),                    // 34: storage.v1.ReadChangesRequest
	(*ReadChangesResponse)(nil),                   // 35: storage.v1.ReadChangesResponse
	(*IsReadyRequest)(nil),                        // 36: storage.v1.IsReadyRequest
	(*IsReadyResponse)(nil),                       // 37: storage.v1.IsReadyResponse
	(*MaxTuplesPerWriteRequest)(nil),              // 38: storage.v1.MaxTuplesPerWriteRequest
	(*MaxTuplesPerWriteResponse)(nil),             // 39: storage.v1.MaxTuplesPerWriteResponse
	(*MaxTypesPerAuthorizationModelRequest)(nil),  // 40: storage.v1.MaxTypesPerAuthorizationModelRequest
	(*MaxTypesPerAuthorizationModelResponse)(nil), // 41: storage.v1.MaxTypesPerAuthorizationModelResponse
	(*ReadFilter)(nil),                            // 42: storage.v1.ReadFilter
	(*ReadUsersetTuplesFilter)(nil),               // 43: storage.v1.ReadUsersetTuplesFilter
	(*ReadStartingWithUserFilter)(nil),            // 44: storage.v1.ReadStartingWithUserFilter
	(*ReadChangesFilter)(nil),                     // 45: storage.v1.ReadChangesFilter
	(*PaginationOptions)(nil),                     // 46: storage.v1.PaginationOptions
	(*ConsistencyOptions)(nil),                    // 47: storage.v1.ConsistencyOptions
	(*TupleWriteOptions)(nil),                     // 48: storage.v1.TupleWriteOptions
	(*Tuple)(nil),                                 // 49: storage.v1.types.Tuple
	(*TupleKey)(nil),                              // 50: storage.v1.types.TupleKey
	(*TupleKeyWithoutCondition)(nil),              // 51: storage.v1.types.TupleKeyWithoutCondition
	(*AuthorizationModel)(nil),                    // 52: storage.v1.types.AuthorizationModel
	(*Store)(nil),                                 // 53: storage.v1.types.Store
	(*Assertion)(nil),                             // 54: storage.v1.types.Assertion
	(*TupleChange)(nil),                           // 55: storage.v1.types.TupleChange
	(*RelationReference)(nil),                     // 56: storage.v1.types.RelationReference
	(*ObjectRelation)(nil),                        // 57: storage.v1.types.ObjectRelation
	(ConsistencyPreference)(0),                    // 58: storage.v1.types.ConsistencyPreference
}
var file_storage_v1_storage_proto_depIdxs = []int32{
	42, // 0: storage.v1.ReadRequest.filter:type_name -> storage.v1.ReadFilter
	47, // 1: storage.v1.ReadRequest.consistency:type_name -> storage.v1.ConsistencyOptions
	49, // 2: storage.v1.ReadResponse.tuple:type_name -> storage.v1.types.Tuple
	42, // 3: storage.v1.ReadPageRequest.filter:type_name -> storage.v1.ReadFilter
	46, // 4: storage.v1.ReadPageRequest.pagination:type_name -> storage.v1.PaginationOptions
	47, // 5: storage.v1.ReadPageRequest.consistency:type_name -> storage.v1.ConsistencyOptions
	49, // 6: storage.v1.ReadPageResponse.tuples:type_name -> storage.v1.types.Tuple
	50, // 7: storage.v1.ReadUserTupleRequest.tuple_key:type_name -> storage.v1.types.TupleKey
	47, // 8: storage.v1.ReadUserTupleRequest.consistency:type_name -> storage.v1.ConsistencyOptions
	49, // 9: storage.v1.ReadUserTupleResponse.tuple:type_name -> storage.v1.types.Tuple
	43, // 10: storage.v1.ReadUsersetTuplesRequest.filter:type_name -> storage.v1.ReadUsersetTuplesFilter
	47, // 11: storage.v1.ReadUsersetTuplesRequest.consistency:type_name -> storage.v1.ConsistencyOptions
	49, // 12: storage.v1.ReadUsersetTuplesResponse.tuple:type_name -> storage.v1.types.Tuple
	44, // 13: storage.v1.ReadStartingWithUserRequest.filter:type_name -> storage.v1.ReadStartingWithUserFilter
	47, // 14: storage.v1.ReadStartingWithUserRequest.consistency:type_name -> storage.v1.ConsistencyOptions
	49, // 15: storage.v1.ReadStartingWithUserResponse.tuple:type_name -> storage.v1.types.Tuple
	51, // 16: storage.v1.WriteRequest.deletes:type_name -> storage.v1.types.TupleKeyWithoutCondition
	50, // 17: storage.v1.WriteRequest.writes:type_name -> storage.v1.types.TupleKey
	48, // 18: storage.v1.WriteRequest.options:type_name -> storage.v1.TupleWriteOptions
	52, // 19: storage.v1.ReadAuthorizationModelResponse.model:type_name -> storage.v1.types.AuthorizationModel
	46, // 20: storage.v1.ReadAuthorizationModelsRequest.pagination:type_name -> storage.v1.PaginationOptions
	52, // 21: storage.v1.ReadAuthorizationModelsResponse.models:type_name -> storage.v1.types.AuthorizationModel
	52, // 22: storage.v1.FindLatestAuthorizationModelResponse.model:type_name -> storage.v1.types.AuthorizationModel
	52, // 23: storage.v1.WriteAuthorizationModelRequest.model:type_name -> storage.v1.types.AuthorizationModel
	53, // 24: storage.v1.CreateStoreRequest.store:type_name -> storage.v1.types.Store
	53, // 25: storage.v1.CreateStoreResponse.store:type_name -> storage.v1.types.Store
	53, // 26: storage.v1.GetStoreResponse.store:type_name -> storage.v1.types.Store
	46, // 27: storage.v1.ListStoresRequest.pagination:type_name -> storage.v1.PaginationOptions
	53, // 28: storage.v1.ListStoresResponse.stores:type_name -> storage.v1.types.Store
	54, // 29: storage.v1.WriteAssertionsRequest.assertions:type_name -> storage.v1.types.Assertion
	54, // 30: storage.v1.ReadAssertionsResponse.assertions:type_name -> storage.v1.types.Assertion
	45, // 31: storage.v1.ReadChangesRequest.filter:type_name -> storage.v1.ReadChangesFilter
	46, // 32: storage.v1.ReadChangesRequest.pagination:type_name -> storage.v1.PaginationOptions
	55, // 33: storage.v1.ReadChangesResponse.changes:type_name -> storage.v1.types.TupleChange
	56, // 34: storage.v1.ReadUsersetTuplesFilter.allowed_user_type_restrictions:type_name -> storage.v1.types.RelationReference
	57, // 35: storage.v1.ReadStartingWithUserFilter.user_filter:type_name -> storage.v1.types.ObjectRelation
	58, // 36: storage.v1.ConsistencyOptions.preference:type_name -> storage.v1.types.ConsistencyPreference
	0,  // 37: storage.v1.TupleWriteOptions.on_missing_delete:type_name -> storage.v1.OnMissingDelete
	1,  // 38: storage.v1.TupleWriteOptions.on_duplicate_insert:type_name -> storage.v1.OnDuplicateInsert
	2,  // 39: storage.v1.StorageService.Read:input_type -> storage.v1.ReadRequest
	4,  // 40: storage.v1.StorageService.ReadPage:input_type -> storage.v1.ReadPageRequest
	6,  // 41: storage.v1.StorageService.ReadUserTuple:input_type -> storage.v1.ReadUserTupleRequest
	8,  // 42: storage.v1.StorageService.ReadUsersetTuples:input_type -> storage.v1.ReadUsersetTuplesRequest
	10, // 43: storage.v1.StorageService.ReadStartingWithUser:input_type -> storage.v1.ReadStartingWithUserRequest
	12, // 44: storage.v1.StorageService.Write:input_type -> storage.v1.WriteRequest
	14, // 45: storage.v1.StorageService.ReadAuthorizationModel:input_type -> storage.v1.ReadAuthorizationModelRequest
	16, // 46: storage.v1.StorageService.ReadAuthorizationModels:input_type -> storage.v1.ReadAuthorizationModelsRequest
	18, // 47: storage.v1.StorageService.FindLatestAuthorizationModel:input_type -> storage.v1.FindLatestAuthorizationModelRequest
	20, // 48: storage.v1.StorageService.WriteAuthorizationModel:input_type -> storage.v1.WriteAuthorizationModelRequest
	22, // 49: storage.v1.StorageService.CreateStore:input_type -> storage.v1.CreateStoreRequest
	24, // 50: storage.v1.StorageService.DeleteStore:input_type -> storage.v1.DeleteStoreRequest
	26, // 51: storage.v1.StorageService.GetStore:input_type -> storage.v1.GetStoreRequest
	28, // 52: storage.v1.StorageService.ListStores:input_type -> storage.v1.ListStoresRequest
	30, // 53: storage.v1.StorageService.WriteAssertions:input_type -> storage.v1.WriteAssertionsRequest
	32, // 54: storage.v1.StorageService.ReadAssertions:input_type -> storage.v1.ReadAssertionsRequest
	34, // 55: storage.v1.StorageService.ReadChanges:input_type -> storage.v1.ReadChangesRequest
	36, // 56: storage.v1.StorageService.IsReady:input_type -> storage.v1.IsReadyRequest
	38, // 57: storage.v1.StorageService.MaxTuplesPerWrite:input_type -> storage.v1.MaxTuplesPerWriteRequest
	40, // 58: storage.v1.StorageService.MaxTypesPerAuthorizationModel:input_type -> storage.v1.MaxTypesPerAuthorizationModelRequest
	3,  // 59: storage.v1.StorageService.Read:output_type -> storage.v1.ReadResponse
	5,  // 60: storage.v1.StorageService.ReadPage:output_type -> storage.v1.ReadPageResponse
	7,  // 61: storage.v1.StorageService.ReadUserTuple:output_type -> storage.v1.ReadUserTupleResponse
	9,  // 62: storage.v1.StorageService.ReadUsersetTuples:output_type -> storage.v1.ReadUsersetTuplesResponse
	11, // 63: storage.v1.StorageService.ReadStartingWithUser:output_type -> storage.v1.ReadStartingWithUserResponse
	13, // 64: storage.v1.StorageService.Write:output_type -> storage.v1.WriteResponse
	15, // 65: storage.v1.StorageService.ReadAuthorizationModel:output_type -> storage.v1.ReadAuthorizationModelResponse
	17, // 66: storage.v1.StorageService.ReadAuthorizationModels:output_type -> storage.v1.ReadAuthorizationModelsResponse
	19, // 67: storage.v1.StorageService.FindLatestAuthorizationModel:output_type -> storage.v1.FindLatestAuthorizationModelResponse
	21, // 68: storage.v1.StorageService.WriteAuthorizationModel:output_type -> storage.v1.WriteAuthorizationModelResponse
	23, // 69: storage.v1.StorageService.CreateStore:output_type -> storage.v1.CreateStoreResponse
	25, // 70: storage.v1.StorageService.DeleteStore:output_type -> storage.v1.DeleteStoreResponse
	27, // 71: storage.v1.StorageService.GetStore:output_type -> storage.v1.GetStoreResponse
	29, // 72: storage.v1.StorageService.ListStores:output_type -> storage.v1.ListStoresResponse
	31, // 73: storage.v1.StorageService.WriteAssertions:output_type -> storage.v1.WriteAssertionsResponse
	33, // 74: storage.v1.StorageService.ReadAssertions:output_type -> storage.v1.ReadAssertionsResponse
	35, // 75: storage.v1.StorageService.ReadChanges:output_type -> storage.v1.ReadChangesResponse
	37, // 76: storage.v1.StorageService.IsReady:output_type -> storage.v1.IsReadyResponse
	39, // 77: storage.v1.StorageService.MaxTuplesPerWrite:output_type -> storage.v1.MaxTuplesPerWriteResponse
	41, // 78: storage.v1.StorageService.MaxTypesPerAuthorizationModel:output_type -> storage.v1.MaxTypesPerAuthorizationModelResponse
	59, // [59:79] is the sub-list for method output_type
	39, // [39:59] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_storage_v1_storage_proto_init() }
func file_storage_v1_storage_proto_init() {
	if File_storage_v1_storage_proto != nil {
		return
	}
	file_storage_v1_openfga_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_v1_storage_proto_rawDesc), len(file_storage_v1_storage_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   47,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_v1_storage_proto_goTypes,
		DependencyIndexes: file_storage_v1_storage_proto_depIdxs,
		EnumInfos:         file_storage_v1_storage_proto_enumTypes,
		MessageInfos:      file_storage_v1_storage_proto_msgTypes,
	}.Build()
	File_storage_v1_storage_proto = out.File
	file_storage_v1_storage_proto_goTypes = nil
	file_storage_v1_storage_proto_depIdxs = nil
}
