// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: storage/v1/storage.proto

package storagev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageService_Read_FullMethodName                          = "/storage.v1.StorageService/Read"
	StorageService_ReadPage_FullMethodName                      = "/storage.v1.StorageService/ReadPage"
	StorageService_ReadUserTuple_FullMethodName                 = "/storage.v1.StorageService/ReadUserTuple"
	StorageService_ReadUsersetTuples_FullMethodName             = "/storage.v1.StorageService/ReadUsersetTuples"
	StorageService_ReadStartingWithUser_FullMethodName          = "/storage.v1.StorageService/ReadStartingWithUser"
	StorageService_Write_FullMethodName                         = "/storage.v1.StorageService/Write"
	StorageService_ReadAuthorizationModel_FullMethodName        = "/storage.v1.StorageService/ReadAuthorizationModel"
	StorageService_ReadAuthorizationModels_FullMethodName       = "/storage.v1.StorageService/ReadAuthorizationModels"
	StorageService_FindLatestAuthorizationModel_FullMethodName  = "/storage.v1.StorageService/FindLatestAuthorizationModel"
	StorageService_WriteAuthorizationModel_FullMethodName       = "/storage.v1.StorageService/WriteAuthorizationModel"
	StorageService_CreateStore_FullMethodName                   = "/storage.v1.StorageService/CreateStore"
	StorageService_DeleteStore_FullMethodName                   = "/storage.v1.StorageService/DeleteStore"
	StorageService_GetStore_FullMethodName                      = "/storage.v1.StorageService/GetStore"
	StorageService_ListStores_FullMethodName                    = "/storage.v1.StorageService/ListStores"
	StorageService_WriteAssertions_FullMethodName               = "/storage.v1.StorageService/WriteAssertions"
	StorageService_ReadAssertions_FullMethodName                = "/storage.v1.StorageService/ReadAssertions"
	StorageService_ReadChanges_FullMethodName                   = "/storage.v1.StorageService/ReadChanges"
	StorageService_IsReady_FullMethodName                       = "/storage.v1.StorageService/IsReady"
	StorageService_MaxTuplesPerWrite_FullMethodName             = "/storage.v1.StorageService/MaxTuplesPerWrite"
	StorageService_MaxTypesPerAuthorizationModel_FullMethodName = "/storage.v1.StorageService/MaxTypesPerAuthorizationModel"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StorageService provides a gRPC interface for OpenFGA's storage backend.
//
// The service is organized into several groups:
// - Tuple operations: Read, ReadPage, ReadUserTuple, ReadUsersetTuples, ReadStartingWithUser, Write
// - Authorization model operations: ReadAuthorizationModel, ReadAuthorizationModels, FindLatestAuthorizationModel, WriteAuthorizationModel
// - Store operations: CreateStore, DeleteStore, GetStore, ListStores
// - Assertion operations: WriteAssertions, ReadAssertions
// - Changelog operations: ReadChanges
// - Service operations: IsReady, MaxTuplesPerWrite, MaxTypesPerAuthorizationModel
type StorageServiceClient interface {
	// Read streams tuples matching the provided filter.
	// Returns an iterator over all matching tuples with no guaranteed order.
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadResponse], error)
	// ReadPage returns a paginated list of tuples matching the filter.
	// Use this when you need bounded result sets with continuation tokens.
	ReadPage(ctx context.Context, in *ReadPageRequest, opts ...grpc.CallOption) (*ReadPageResponse, error)
	// ReadUserTuple returns exactly one tuple matching the provided key.
	// Returns NOT_FOUND error if no matching tuple exists.
	ReadUserTuple(ctx context.Context, in *ReadUserTupleRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	// ReadUsersetTuples streams userset tuples for a specified object and relation.
	// Can be filtered by allowed user type restrictions.
	ReadUsersetTuples(ctx context.Context, in *ReadUsersetTuplesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadResponse], error)
	// ReadStartingWithUser performs a reverse read starting from user(s)/userset(s).
	// Useful for finding all objects a user has access to.
	ReadStartingWithUser(ctx context.Context, in *ReadStartingWithUserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadResponse], error)
	// Write performs tuple write and delete operations atomically.
	// All deletes are performed before writes.
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	// ReadAuthorizationModel retrieves a specific authorization model by ID.
	ReadAuthorizationModel(ctx context.Context, in *ReadAuthorizationModelRequest, opts ...grpc.CallOption) (*ReadAuthorizationModelResponse, error)
	// ReadAuthorizationModels returns all authorization models for a store.
	// Models are returned in descending order (newest first).
	ReadAuthorizationModels(ctx context.Context, in *ReadAuthorizationModelsRequest, opts ...grpc.CallOption) (*ReadAuthorizationModelsResponse, error)
	// FindLatestAuthorizationModel returns the most recent authorization model for a store.
	FindLatestAuthorizationModel(ctx context.Context, in *FindLatestAuthorizationModelRequest, opts ...grpc.CallOption) (*FindLatestAuthorizationModelResponse, error)
	// WriteAuthorizationModel creates a new authorization model version.
	WriteAuthorizationModel(ctx context.Context, in *WriteAuthorizationModelRequest, opts ...grpc.CallOption) (*WriteAuthorizationModelResponse, error)
	// CreateStore creates a new OpenFGA store.
	CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*CreateStoreResponse, error)
	// DeleteStore deletes a store (soft delete).
	DeleteStore(ctx context.Context, in *DeleteStoreRequest, opts ...grpc.CallOption) (*DeleteStoreResponse, error)
	// GetStore retrieves a store by ID.
	GetStore(ctx context.Context, in *GetStoreRequest, opts ...grpc.CallOption) (*GetStoreResponse, error)
	// ListStores returns a paginated list of stores.
	ListStores(ctx context.Context, in *ListStoresRequest, opts ...grpc.CallOption) (*ListStoresResponse, error)
	// WriteAssertions writes test assertions for an authorization model.
	WriteAssertions(ctx context.Context, in *WriteAssertionsRequest, opts ...grpc.CallOption) (*WriteAssertionsResponse, error)
	// ReadAssertions retrieves assertions for a specific authorization model.
	ReadAssertions(ctx context.Context, in *ReadAssertionsRequest, opts ...grpc.CallOption) (*ReadAssertionsResponse, error)
	// ReadChanges returns tuple changes (writes and deletes) in chronological order.
	ReadChanges(ctx context.Context, in *ReadChangesRequest, opts ...grpc.CallOption) (*ReadChangesResponse, error)
	// IsReady checks if the storage backend is ready to accept requests.
	IsReady(ctx context.Context, in *IsReadyRequest, opts ...grpc.CallOption) (*IsReadyResponse, error)
	// MaxTuplesPerWrite returns the maximum number of tuple operations per Write call.
	MaxTuplesPerWrite(ctx context.Context, in *MaxTuplesPerWriteRequest, opts ...grpc.CallOption) (*MaxTuplesPerWriteResponse, error)
	// MaxTypesPerAuthorizationModel returns the maximum number of types per authorization model.
	MaxTypesPerAuthorizationModel(ctx context.Context, in *MaxTypesPerAuthorizationModelRequest, opts ...grpc.CallOption) (*MaxTypesPerAuthorizationModelResponse, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[0], StorageService_Read_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadRequest, ReadResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_ReadClient = grpc.ServerStreamingClient[ReadResponse]

func (c *storageServiceClient) ReadPage(ctx context.Context, in *ReadPageRequest, opts ...grpc.CallOption) (*ReadPageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadPageResponse)
	err := c.cc.Invoke(ctx, StorageService_ReadPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ReadUserTuple(ctx context.Context, in *ReadUserTupleRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, StorageService_ReadUserTuple_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ReadUsersetTuples(ctx context.Context, in *ReadUsersetTuplesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[1], StorageService_ReadUsersetTuples_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadUsersetTuplesRequest, ReadResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_ReadUsersetTuplesClient = grpc.ServerStreamingClient[ReadResponse]

func (c *storageServiceClient) ReadStartingWithUser(ctx context.Context, in *ReadStartingWithUserRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[2], StorageService_ReadStartingWithUser_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadStartingWithUserRequest, ReadResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_ReadStartingWithUserClient = grpc.ServerStreamingClient[ReadResponse]

func (c *storageServiceClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteResponse)
	err := c.cc.Invoke(ctx, StorageService_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ReadAuthorizationModel(ctx context.Context, in *ReadAuthorizationModelRequest, opts ...grpc.CallOption) (*ReadAuthorizationModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadAuthorizationModelResponse)
	err := c.cc.Invoke(ctx, StorageService_ReadAuthorizationModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ReadAuthorizationModels(ctx context.Context, in *ReadAuthorizationModelsRequest, opts ...grpc.CallOption) (*ReadAuthorizationModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadAuthorizationModelsResponse)
	err := c.cc.Invoke(ctx, StorageService_ReadAuthorizationModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) FindLatestAuthorizationModel(ctx context.Context, in *FindLatestAuthorizationModelRequest, opts ...grpc.CallOption) (*FindLatestAuthorizationModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindLatestAuthorizationModelResponse)
	err := c.cc.Invoke(ctx, StorageService_FindLatestAuthorizationModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) WriteAuthorizationModel(ctx context.Context, in *WriteAuthorizationModelRequest, opts ...grpc.CallOption) (*WriteAuthorizationModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteAuthorizationModelResponse)
	err := c.cc.Invoke(ctx, StorageService_WriteAuthorizationModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) CreateStore(ctx context.Context, in *CreateStoreRequest, opts ...grpc.CallOption) (*CreateStoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateStoreResponse)
	err := c.cc.Invoke(ctx, StorageService_CreateStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DeleteStore(ctx context.Context, in *DeleteStoreRequest, opts ...grpc.CallOption) (*DeleteStoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStoreResponse)
	err := c.cc.Invoke(ctx, StorageService_DeleteStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) GetStore(ctx context.Context, in *GetStoreRequest, opts ...grpc.CallOption) (*GetStoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStoreResponse)
	err := c.cc.Invoke(ctx, StorageService_GetStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ListStores(ctx context.Context, in *ListStoresRequest, opts ...grpc.CallOption) (*ListStoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStoresResponse)
	err := c.cc.Invoke(ctx, StorageService_ListStores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) WriteAssertions(ctx context.Context, in *WriteAssertionsRequest, opts ...grpc.CallOption) (*WriteAssertionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteAssertionsResponse)
	err := c.cc.Invoke(ctx, StorageService_WriteAssertions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ReadAssertions(ctx context.Context, in *ReadAssertionsRequest, opts ...grpc.CallOption) (*ReadAssertionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadAssertionsResponse)
	err := c.cc.Invoke(ctx, StorageService_ReadAssertions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ReadChanges(ctx context.Context, in *ReadChangesRequest, opts ...grpc.CallOption) (*ReadChangesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadChangesResponse)
	err := c.cc.Invoke(ctx, StorageService_ReadChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) IsReady(ctx context.Context, in *IsReadyRequest, opts ...grpc.CallOption) (*IsReadyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsReadyResponse)
	err := c.cc.Invoke(ctx, StorageService_IsReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) MaxTuplesPerWrite(ctx context.Context, in *MaxTuplesPerWriteRequest, opts ...grpc.CallOption) (*MaxTuplesPerWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaxTuplesPerWriteResponse)
	err := c.cc.Invoke(ctx, StorageService_MaxTuplesPerWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) MaxTypesPerAuthorizationModel(ctx context.Context, in *MaxTypesPerAuthorizationModelRequest, opts ...grpc.CallOption) (*MaxTypesPerAuthorizationModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MaxTypesPerAuthorizationModelResponse)
	err := c.cc.Invoke(ctx, StorageService_MaxTypesPerAuthorizationModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations must embed UnimplementedStorageServiceServer
// for forward compatibility.
//
// StorageService provides a gRPC interface for OpenFGA's storage backend.
//
// The service is organized into several groups:
// - Tuple operations: Read, ReadPage, ReadUserTuple, ReadUsersetTuples, ReadStartingWithUser, Write
// - Authorization model operations: ReadAuthorizationModel, ReadAuthorizationModels, FindLatestAuthorizationModel, WriteAuthorizationModel
// - Store operations: CreateStore, DeleteStore, GetStore, ListStores
// - Assertion operations: WriteAssertions, ReadAssertions
// - Changelog operations: ReadChanges
// - Service operations: IsReady, MaxTuplesPerWrite, MaxTypesPerAuthorizationModel
type StorageServiceServer interface {
	// Read streams tuples matching the provided filter.
	// Returns an iterator over all matching tuples with no guaranteed order.
	Read(*ReadRequest, grpc.ServerStreamingServer[ReadResponse]) error
	// ReadPage returns a paginated list of tuples matching the filter.
	// Use this when you need bounded result sets with continuation tokens.
	ReadPage(context.Context, *ReadPageRequest) (*ReadPageResponse, error)
	// ReadUserTuple returns exactly one tuple matching the provided key.
	// Returns NOT_FOUND error if no matching tuple exists.
	ReadUserTuple(context.Context, *ReadUserTupleRequest) (*ReadResponse, error)
	// ReadUsersetTuples streams userset tuples for a specified object and relation.
	// Can be filtered by allowed user type restrictions.
	ReadUsersetTuples(*ReadUsersetTuplesRequest, grpc.ServerStreamingServer[ReadResponse]) error
	// ReadStartingWithUser performs a reverse read starting from user(s)/userset(s).
	// Useful for finding all objects a user has access to.
	ReadStartingWithUser(*ReadStartingWithUserRequest, grpc.ServerStreamingServer[ReadResponse]) error
	// Write performs tuple write and delete operations atomically.
	// All deletes are performed before writes.
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	// ReadAuthorizationModel retrieves a specific authorization model by ID.
	ReadAuthorizationModel(context.Context, *ReadAuthorizationModelRequest) (*ReadAuthorizationModelResponse, error)
	// ReadAuthorizationModels returns all authorization models for a store.
	// Models are returned in descending order (newest first).
	ReadAuthorizationModels(context.Context, *ReadAuthorizationModelsRequest) (*ReadAuthorizationModelsResponse, error)
	// FindLatestAuthorizationModel returns the most recent authorization model for a store.
	FindLatestAuthorizationModel(context.Context, *FindLatestAuthorizationModelRequest) (*FindLatestAuthorizationModelResponse, error)
	// WriteAuthorizationModel creates a new authorization model version.
	WriteAuthorizationModel(context.Context, *WriteAuthorizationModelRequest) (*WriteAuthorizationModelResponse, error)
	// CreateStore creates a new OpenFGA store.
	CreateStore(context.Context, *CreateStoreRequest) (*CreateStoreResponse, error)
	// DeleteStore deletes a store (soft delete).
	DeleteStore(context.Context, *DeleteStoreRequest) (*DeleteStoreResponse, error)
	// GetStore retrieves a store by ID.
	GetStore(context.Context, *GetStoreRequest) (*GetStoreResponse, error)
	// ListStores returns a paginated list of stores.
	ListStores(context.Context, *ListStoresRequest) (*ListStoresResponse, error)
	// WriteAssertions writes test assertions for an authorization model.
	WriteAssertions(context.Context, *WriteAssertionsRequest) (*WriteAssertionsResponse, error)
	// ReadAssertions retrieves assertions for a specific authorization model.
	ReadAssertions(context.Context, *ReadAssertionsRequest) (*ReadAssertionsResponse, error)
	// ReadChanges returns tuple changes (writes and deletes) in chronological order.
	ReadChanges(context.Context, *ReadChangesRequest) (*ReadChangesResponse, error)
	// IsReady checks if the storage backend is ready to accept requests.
	IsReady(context.Context, *IsReadyRequest) (*IsReadyResponse, error)
	// MaxTuplesPerWrite returns the maximum number of tuple operations per Write call.
	MaxTuplesPerWrite(context.Context, *MaxTuplesPerWriteRequest) (*MaxTuplesPerWriteResponse, error)
	// MaxTypesPerAuthorizationModel returns the maximum number of types per authorization model.
	MaxTypesPerAuthorizationModel(context.Context, *MaxTypesPerAuthorizationModelRequest) (*MaxTypesPerAuthorizationModelResponse, error)
	mustEmbedUnimplementedStorageServiceServer()
}

// UnimplementedStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageServiceServer struct{}

func (UnimplementedStorageServiceServer) Read(*ReadRequest, grpc.ServerStreamingServer[ReadResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedStorageServiceServer) ReadPage(context.Context, *ReadPageRequest) (*ReadPageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPage not implemented")
}
func (UnimplementedStorageServiceServer) ReadUserTuple(context.Context, *ReadUserTupleRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadUserTuple not implemented")
}
func (UnimplementedStorageServiceServer) ReadUsersetTuples(*ReadUsersetTuplesRequest, grpc.ServerStreamingServer[ReadResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ReadUsersetTuples not implemented")
}
func (UnimplementedStorageServiceServer) ReadStartingWithUser(*ReadStartingWithUserRequest, grpc.ServerStreamingServer[ReadResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ReadStartingWithUser not implemented")
}
func (UnimplementedStorageServiceServer) Write(context.Context, *WriteRequest) (*WriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedStorageServiceServer) ReadAuthorizationModel(context.Context, *ReadAuthorizationModelRequest) (*ReadAuthorizationModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAuthorizationModel not implemented")
}
func (UnimplementedStorageServiceServer) ReadAuthorizationModels(context.Context, *ReadAuthorizationModelsRequest) (*ReadAuthorizationModelsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAuthorizationModels not implemented")
}
func (UnimplementedStorageServiceServer) FindLatestAuthorizationModel(context.Context, *FindLatestAuthorizationModelRequest) (*FindLatestAuthorizationModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindLatestAuthorizationModel not implemented")
}
func (UnimplementedStorageServiceServer) WriteAuthorizationModel(context.Context, *WriteAuthorizationModelRequest) (*WriteAuthorizationModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteAuthorizationModel not implemented")
}
func (UnimplementedStorageServiceServer) CreateStore(context.Context, *CreateStoreRequest) (*CreateStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStore not implemented")
}
func (UnimplementedStorageServiceServer) DeleteStore(context.Context, *DeleteStoreRequest) (*DeleteStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteStore not implemented")
}
func (UnimplementedStorageServiceServer) GetStore(context.Context, *GetStoreRequest) (*GetStoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStore not implemented")
}
func (UnimplementedStorageServiceServer) ListStores(context.Context, *ListStoresRequest) (*ListStoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStores not implemented")
}
func (UnimplementedStorageServiceServer) WriteAssertions(context.Context, *WriteAssertionsRequest) (*WriteAssertionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteAssertions not implemented")
}
func (UnimplementedStorageServiceServer) ReadAssertions(context.Context, *ReadAssertionsRequest) (*ReadAssertionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAssertions not implemented")
}
func (UnimplementedStorageServiceServer) ReadChanges(context.Context, *ReadChangesRequest) (*ReadChangesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadChanges not implemented")
}
func (UnimplementedStorageServiceServer) IsReady(context.Context, *IsReadyRequest) (*IsReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReady not implemented")
}
func (UnimplementedStorageServiceServer) MaxTuplesPerWrite(context.Context, *MaxTuplesPerWriteRequest) (*MaxTuplesPerWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaxTuplesPerWrite not implemented")
}
func (UnimplementedStorageServiceServer) MaxTypesPerAuthorizationModel(context.Context, *MaxTypesPerAuthorizationModelRequest) (*MaxTypesPerAuthorizationModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaxTypesPerAuthorizationModel not implemented")
}
func (UnimplementedStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {}
func (UnimplementedStorageServiceServer) testEmbeddedByValue()                        {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	// If the following call pancis, it indicates UnimplementedStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).Read(m, &grpc.GenericServerStream[ReadRequest, ReadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_ReadServer = grpc.ServerStreamingServer[ReadResponse]

func _StorageService_ReadPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ReadPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ReadPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ReadPage(ctx, req.(*ReadPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ReadUserTuple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadUserTupleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ReadUserTuple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ReadUserTuple_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ReadUserTuple(ctx, req.(*ReadUserTupleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ReadUsersetTuples_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadUsersetTuplesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).ReadUsersetTuples(m, &grpc.GenericServerStream[ReadUsersetTuplesRequest, ReadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_ReadUsersetTuplesServer = grpc.ServerStreamingServer[ReadResponse]

func _StorageService_ReadStartingWithUser_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadStartingWithUserRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).ReadStartingWithUser(m, &grpc.GenericServerStream[ReadStartingWithUserRequest, ReadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_ReadStartingWithUserServer = grpc.ServerStreamingServer[ReadResponse]

func _StorageService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).Write(ctx, req.(*WriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ReadAuthorizationModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAuthorizationModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ReadAuthorizationModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ReadAuthorizationModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ReadAuthorizationModel(ctx, req.(*ReadAuthorizationModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ReadAuthorizationModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAuthorizationModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ReadAuthorizationModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ReadAuthorizationModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ReadAuthorizationModels(ctx, req.(*ReadAuthorizationModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_FindLatestAuthorizationModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindLatestAuthorizationModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).FindLatestAuthorizationModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_FindLatestAuthorizationModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).FindLatestAuthorizationModel(ctx, req.(*FindLatestAuthorizationModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_WriteAuthorizationModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteAuthorizationModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).WriteAuthorizationModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_WriteAuthorizationModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).WriteAuthorizationModel(ctx, req.(*WriteAuthorizationModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_CreateStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CreateStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_CreateStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CreateStore(ctx, req.(*CreateStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DeleteStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DeleteStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_DeleteStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DeleteStore(ctx, req.(*DeleteStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_GetStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).GetStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_GetStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).GetStore(ctx, req.(*GetStoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ListStores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ListStores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ListStores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ListStores(ctx, req.(*ListStoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_WriteAssertions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteAssertionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).WriteAssertions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_WriteAssertions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).WriteAssertions(ctx, req.(*WriteAssertionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ReadAssertions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAssertionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ReadAssertions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ReadAssertions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ReadAssertions(ctx, req.(*ReadAssertionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ReadChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ReadChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ReadChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ReadChanges(ctx, req.(*ReadChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_IsReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).IsReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_IsReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).IsReady(ctx, req.(*IsReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_MaxTuplesPerWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaxTuplesPerWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).MaxTuplesPerWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_MaxTuplesPerWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).MaxTuplesPerWrite(ctx, req.(*MaxTuplesPerWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_MaxTypesPerAuthorizationModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaxTypesPerAuthorizationModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).MaxTypesPerAuthorizationModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_MaxTypesPerAuthorizationModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).MaxTypesPerAuthorizationModel(ctx, req.(*MaxTypesPerAuthorizationModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.v1.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadPage",
			Handler:    _StorageService_ReadPage_Handler,
		},
		{
			MethodName: "ReadUserTuple",
			Handler:    _StorageService_ReadUserTuple_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _StorageService_Write_Handler,
		},
		{
			MethodName: "ReadAuthorizationModel",
			Handler:    _StorageService_ReadAuthorizationModel_Handler,
		},
		{
			MethodName: "ReadAuthorizationModels",
			Handler:    _StorageService_ReadAuthorizationModels_Handler,
		},
		{
			MethodName: "FindLatestAuthorizationModel",
			Handler:    _StorageService_FindLatestAuthorizationModel_Handler,
		},
		{
			MethodName: "WriteAuthorizationModel",
			Handler:    _StorageService_WriteAuthorizationModel_Handler,
		},
		{
			MethodName: "CreateStore",
			Handler:    _StorageService_CreateStore_Handler,
		},
		{
			MethodName: "DeleteStore",
			Handler:    _StorageService_DeleteStore_Handler,
		},
		{
			MethodName: "GetStore",
			Handler:    _StorageService_GetStore_Handler,
		},
		{
			MethodName: "ListStores",
			Handler:    _StorageService_ListStores_Handler,
		},
		{
			MethodName: "WriteAssertions",
			Handler:    _StorageService_WriteAssertions_Handler,
		},
		{
			MethodName: "ReadAssertions",
			Handler:    _StorageService_ReadAssertions_Handler,
		},
		{
			MethodName: "ReadChanges",
			Handler:    _StorageService_ReadChanges_Handler,
		},
		{
			MethodName: "IsReady",
			Handler:    _StorageService_IsReady_Handler,
		},
		{
			MethodName: "MaxTuplesPerWrite",
			Handler:    _StorageService_MaxTuplesPerWrite_Handler,
		},
		{
			MethodName: "MaxTypesPerAuthorizationModel",
			Handler:    _StorageService_MaxTypesPerAuthorizationModel_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Read",
			Handler:       _StorageService_Read_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadUsersetTuples",
			Handler:       _StorageService_ReadUsersetTuples_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReadStartingWithUser",
			Handler:       _StorageService_ReadStartingWithUser_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "storage/v1/storage.proto",
}
