{
 "title": "OpenFGA Dashboard",
 "time": { "from": "now-20m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Server Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS per Method",
   "type": "timeseries",
   "description": "The number of requests per second (aggregated over a 1m interval) per method.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"openfga\",grpc_service=\"openfga.v1.OpenFGAService\"}[1m])) by (grpc_method)\n",
     "legendFormat": "openfga.v1.OpenFGAService/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "p50 RPC Request Duration by Method",
   "type": "timeseries",
   "description": "The 50th percentile request duration of an RPC, grouped by 'grpc_service' and 'grpc_method'.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, grpc_method, grpc_service) (rate(grpc_server_handling_seconds_bucket{job=\"openfga\", grpc_type=\"unary\"}[2m])))",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "p90 RPC Request Duration by Method",
   "type": "timeseries",
   "description": "The 90th percentile request duration of an RPC, grouped by 'grpc_service' and 'grpc_method'.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le, grpc_method, grpc_service) (rate(grpc_server_handling_seconds_bucket{job=\"openfga\", grpc_type=\"unary\", grpc_service=\"openfga.v1.OpenFGAService\"}[2m])))",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "p99 RPC Request Duration by Method",
   "type": "timeseries",
   "description": "The 99th percentile request duration of an RPC, grouped by 'grpc_service' and 'grpc_method'.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, grpc_method, grpc_service) (rate(grpc_server_handling_seconds_bucket{job=\"openfga\", grpc_type=\"unary\", grpc_service=\"openfga.v1.OpenFGAService\"}[2m])))",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}"
    }
   ]
  },
  { "title": "Go Runtime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Go Process Max File Descriptors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_max_fds{job=\"openfga\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go Process Open File Descriptors",
   "type": "stat",
   "description": "The number of open file descriptors the Go process has.",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{job=\"openfga\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "The number of goroutines reported by the Go runtime.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"openfga\"}",
     "legendFormat": "Goroutines (Count)"
    },
    {
     "expr": "irate(go_goroutines{job=\"openfga\"}[2m])",
     "legendFormat": "Goroutine (Derivative)"
    }
   ]
  },
  {
   "title": "Go GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"openfga\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"openfga\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"openfga\", quantile=\"1\"}",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"openfga\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Heap Allocation Rate (bytes/sec)",
   "type": "timeseries",
   "description": "Shows the number of heap allocations (as a byte/sec rate).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"openfga\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Allocation Rate (malloc/sec)",
   "type": "timeseries",
   "description": "The number of heap allocations (mallocs) as a rate (malloc/sec).",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=\"openfga\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}