// Package dsql provides shared utilities for Aurora DSQL connections.
package dsql

import (
	"context"
	"database/sql"
	"fmt"
	"net/url"
	"strings"

	"github.com/awslabs/aurora-dsql-connectors/go/pgx/dsql"
)

// PreparePostgresURI converts a dsql:// URI to a postgres:// URI with IAM authentication.
// If username is provided, it overrides any username in the URI for token generation.
func PreparePostgresURI(uri string, username string) (string, error) {
	// Inject username into URI for token generation if provided.
	tokenURI := uri
	if username != "" {
		pgURI := "postgres" + strings.TrimPrefix(uri, "dsql")
		parsed, err := url.Parse(pgURI)
		if err != nil {
			return "", fmt.Errorf("parse URI for username override: %w", err)
		}
		parsed.User = url.User(username)
		tokenURI = "dsql" + strings.TrimPrefix(parsed.String(), "postgres")
	}

	token, err := dsql.GenerateTokenConnString(context.Background(), tokenURI)
	if err != nil {
		return "", fmt.Errorf("generate DSQL auth token: %w", err)
	}

	pgURI := "postgres" + strings.TrimPrefix(uri, "dsql")
	dbURI, err := url.Parse(pgURI)
	if err != nil {
		return "", fmt.Errorf("parse database URI: %w", err)
	}

	// Determine final username: param > URI > default "admin"
	finalUser := username
	if finalUser == "" {
		if dbURI.User != nil {
			finalUser = dbURI.User.Username()
		}
		if finalUser == "" {
			finalUser = "admin"
		}
	}
	dbURI.User = url.UserPassword(finalUser, token)

	q := dbURI.Query()
	q.Set("sslmode", "require")
	q.Del("region")
	dbURI.RawQuery = q.Encode()

	return dbURI.String(), nil
}

// GooseTableDDL is the DDL for creating a DSQL-compatible goose version table.
// Uses BIGINT GENERATED BY DEFAULT AS IDENTITY, as required by DSQL.
const GooseTableDDL = `
	CREATE TABLE IF NOT EXISTS goose_db_version (
		id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY,
		version_id BIGINT NOT NULL,
		is_applied BOOLEAN NOT NULL,
		tstamp TIMESTAMP DEFAULT now()
	)
`

// EnsureGooseTable creates the goose_db_version table if it doesn't exist.
func EnsureGooseTable(db *sql.DB) error {
	if _, err := db.Exec(GooseTableDDL); err != nil {
		return fmt.Errorf("create goose table: %w", err)
	}

	// Goose expects an initial row with version 0 to exist.
	var hasRows bool
	if err := db.QueryRow(`SELECT EXISTS (SELECT 1 FROM goose_db_version)`).Scan(&hasRows); err != nil {
		return fmt.Errorf("check goose table: %w", err)
	}

	if !hasRows {
		if _, err := db.Exec(`INSERT INTO goose_db_version (version_id, is_applied) VALUES (0, TRUE)`); err != nil {
			return fmt.Errorf("insert initial goose row: %w", err)
		}
	}

	return nil
}
