name: Check Markdown links

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 9 * * 1" # At 09:00 on Monday

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: gaurav-nelson/github-action-markdown-link-check@3c3b66f1f7d0900e37b71eca45b63ea9eedfce31 # v1.0.17
        with:
          use-verbose-mode: 'yes'
          folder-path: 'docs/'
          file-path: './README.md, ./CHANGELOG.md'
          config-file: '.github/.mlc_config.json'
